### ISSUE TITLE
Tutorial on how to create a simple one-player game and how to run it in Cosmic-Swingset

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/Documentation#1]
A couple of questions i cannot answer yet:
- is `{try(attempt){return attempt === 37 ? 'you win' : 'you lose'}` a "valid" contract?
    - currently? eventually?
- is Swingset a requirement to run contracts?
- Do contracts need to be written in Jessie?
    - currently? eventually?

**Comment by Chris-Hibbert** [comment]
more like this:

```
const questions = harden({
  start: (inviteMaker) => {
    const seat = harden({ 
        guess() {
			try (attempt) {
			  return attempt === 37 ? 'you win' : 'you lose';
			}
		},
    });

    return harden({
      player: inviteMaker.make('player', seat),
    });
  },
});

const escrowExchangeSrcs = harden({
  start: `${questions.start}`,
});

export { escrowExchangeSrcs };
```

**Comment by erights** [comment]
```js
try (attempt) {
```

is not currently valid JavaScript syntax. There's a proposal that would use this syntax, but it is a long way from being approved.

```js
start: (inviteMaker) => {
```
should be
```js
start: (terms, inviteMaker) => {
```
```
