### ISSUE TITLE
UI Component Documentation

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/documentation#1000]
Drafting in [UI Components Documentation](https://docs.google.com/document/d/1vXr6WmLJk9Kf8NQ5uvGH2Pmiex0wQnOA1qdUdPLEOT0/edit?usp=sharing)

**Comment by dckc** [comment]
I wonder how this relates to

 - #922

dup?

**Comment by samsiegart** [comment]
I've just added screenshots and parameter tables to [UI Components Documentation](https://docs.google.com/document/d/1vXr6WmLJk9Kf8NQ5uvGH2Pmiex0wQnOA1qdUdPLEOT0/edit?usp=sharing)
