### ISSUE TITLE
Reference missing from left nav bar

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#1005]
the Zoe API reference etc. is gone from the left nav bar.
another regression from #971 ?

cc @0xpatrickdev

**Comment by 0xpatrickdev** [comment]
I think it's still there - we have a sidebar for `guides` and another for `reference`. I am able to see it on https://docs.agoric.com/reference/ertp-api/.

As part of #973, I think it would be nice keep multiple sidebars. If I click one of "Tutorials", "Core Concepts", or "How To" on the top-nav, I should see a sidebar dedicated to each's contents.

**Comment by 0xpatrickdev** [comment]
> I think it would be nice keep multiple sidebars. If I click one of "Tutorials", "Core Concepts", or "How To" on the top-nav, I should see a sidebar dedicated to each's contents.

Here are two examples of this: 
- https://vitepress.dev/ ([Guide](https://vitepress.dev/guide/what-is-vitepress), [Reference](https://vitepress.dev/reference/site-config))
- https://vitejs.dev/  ([Guide](https://vitejs.dev/guide/), [Config](https://vitejs.dev/config/), Plugins, + Resources for external links)

**Comment by dckc** [comment]
fixed along with #973
