### ISSUE TITLE
Provide examples of how to use Keywords (zoe) properly

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#102]
What do keywords represent? Is it roles in the contract? Various "asset types"? Something else?

**Comment by Chris-Hibbert** [comment]
They're roles that issuers play within the contract. A single issuer might appear in more than one role in a particular instance of the contract, but the keywords allow the contract author to keep track separately of money that's being used to pay for goods as opposed to payments for a seat, for example. 

The contract writer has to distinguish them during development so they can be distinguished and separately balanced. When an instance of the contract is running, each particular role will have a separate balance that will be conserved, even when a single currency is used in more than one role.

**Comment by katelynsills** [comment]
@DavidBruant We do have some documentation on keywords, for instance, in Offer Safety: https://agoric.com/documentation/zoe/guide/offer-safety.html#offer-safety

This is probably not sufficient though. Where should we add more documentation and what should we say?

**Comment by katelynsills** [comment]
I think Tom's intro to Zoe guide will cover part of this. We should take a look at the current documentation and see if we still need more.

**Comment by DavidBruant** [comment]
> The keyword record is made up of two key:value pairs. The key names must be ASCII and capitalized; they are the same as are used in the contract code, in this case Price and Asset. Price is for what is wanted, and Asset is for what is being sold. Price is for what will be swapped for it (from the perspective of the user making the instance; it’d be the opposite for someone who wanted what Alice is offering). The price is denominated in simoleons, so that keyword needs the simoleon Issuer associated with it. The asset is denominated in moola, so that keyword needs the moola Issuer as its value.

https://agoric.com/documentation/getting-started/intro-zoe.html#installing-and-instantiating-contracts-on-zoe

And there is nothing about keywords at https://agoric.com/documentation/zoe/guide/#how-to-write-smart-contracts (possibly because this text hasn't been updated in a long time)

I feel like an explanation of what choices would be good for keywords (and the fact that they refer to roles in the contract) would be good

**Comment by katelynsills** [comment]
Ok, both of those things sound good to me. I would want to coordinate with the changes that Tom is planning to make to that doc.

**Comment by tyg** [comment]
Closing this out, as a serious reworking of How To Write Smart Contracts is covered elsewhere and will certainly include keywords.
