### ISSUE TITLE
[Zoe] Explain how exit options are reflected

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#103]
[Something is added to the redemption object](https://github.com/Agoric/agoric-sdk/blob/7ceebe5f45333525eb59a9d6ec7a062f93ea2da7/packages/zoe/src/zoe.js#L426-L458)

I haven't seen it in the doc

**Comment by DavidBruant** [comment]
related: https://github.com/Agoric/agoric-sdk/issues/818

**Comment by katelynsills** [comment]
Yeah, this very much needs to be documented. Thank you for the issue!

**Comment by katelynsills** [comment]
Explained in both the Zoe API and Guide now
