### ISSUE TITLE
continuous publishing for api-docs in ui-kit

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/documentation#1047]
like https://agoric-sdk.pages.dev but for ui-kit

----
_earlier_
You know, like #1032, but for ui-kit repo

**Comment by dckc** [comment]
@turadg here's hoping you get to this before I do...

**Comment by dckc** [comment]
@toliaqat here's hoping you get to this before I do...

**Comment by toliaqat** [comment]
Doc deployments added in CF pages. https://ui-kit-dwm.pages.dev/
PRs will get review pages as well.

**Comment by dckc** [comment]
yay!
