### ISSUE TITLE
describe upgrade contract meta info

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#1126]
Contracts originally were required to return a `start` function. At some point, we changed the name to `prepare` to signal upgradeability. [#8045](https://github.com/Agoric/agoric-sdk/pull/8045) changed it back to start, but included support for `prepare` for backwards compatibility. The use of `meta` to contain details of the upgradeability didn't make it into the docs. 

Change the [documentation on contract upgrade](https://docs.agoric.com/guides/zoe/contract-upgrade#upgradable-contracts) to specify `start`, and to describe the use of `meta`.

**Comment by dckc** [comment]
It looks like the relevant Zoe upgrade went out in [upgrade 14](https://github.com/Agoric/agoric-sdk/releases/tag/agoric-upgrade-14) / `d69c011` [proposal 71](https://ping.pub/agoric/gov/71) 2024-03-30.
