### ISSUE TITLE
Put the TimerService docs somewhere devs can find it

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#114]
https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/TimerService.md

**Comment by tyg** [comment]
Content put in REPL doc draft.

**Comment by Chris-Hibbert** [comment]
Let's not close this issue until the doc has been made public. If it has and I missed it, please add a link to the PR or the public doc.

**Comment by tyg** [comment]
In REPL docs in Github
