### ISSUE TITLE
orch examples outdated by migration from provideOrchestration to withOrchestration

### ISSUE THREAD

**Issue by amessbee** [Agoric/documentation#1154]
[Cross Chain Swap](https://docs.agoric.com/guides/orchestration/getting-started/contract-walkthrough/cross-chain-swap.html) and [Cross Chain Unbond](https://docs.agoric.com/guides/orchestration/getting-started/contract-walkthrough/cross-chain-unbond.html) walkthroughs are outdated due to a recent merge on `agoric-sdk`. They need to be updated to reflect new API in use.

**Comment by dckc** [comment]
help me out a bit? which recent merge? outdated in what way?

**Comment by dckc** [comment]
would "orch examples outdated by migration from provideOrchestration to withOrchestration" be an accurate title?
