### ISSUE TITLE
Updates to Agoric Getting started for Mac

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/documentation#1161]
## What is the Problem Being Solved?
Original Incidents:

Running the [getting started tutorial](https://docs.agoric.com/guides/getting-started/) for Mac I ran into two issues. The first is easy to get past and the second has me stuck. Im sure its user error, but figured I would put it here in case its something we could/should update.

Installing Docker
- docs say run "brew cask install docker”
- Returns Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
- Reran with “brew install docker --cask” and works fine

Adding User Account to Docker Group
- docs say run % sudo usermod -aG docker $USER
- Returns error “sudo: usermod: command not found”
- further steps do not run, not sure how to get past this

After this pull request https://github.com/Agoric/documentation/pull/1160 I follow these steps in the new guide and get the below. Docker is already installed per the message, but when I run hello world, I get this error. 

```console
ajrumph@AJs-MacBook-Pro ~ % brew install docker --cask
Warning: Not upgrading docker, the latest version is already installed
ajrumph@AJs-MacBook-Pro ~ % docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.


ajrumph@AJs-MacBook-Pro ~ % brew install docker --cask
Warning: Not upgrading docker, the latest version is already installed
ajrumph@AJs-MacBook-Pro ~ % docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

## Upgrade Considerations
Does not require an  a chain stopping upgrade

**Comment by Jovonni** [comment]
@aj-agoric 
thats just saying to make sure your docker daemon is actually running:
[docker with brew](https://www.cprime.com/resources/blog/docker-for-mac-with-homebrew-a-step-by-step-tutorial/#:~:text=You%20can%20start%20using%20Docker,start%20automatically%20with%20system%20startup.)

Using Docker Desktop may help you here, as it has a UI to help learn your way around as well:
[install docker desktop](https://docs.docker.com/desktop/install/mac-install/)

**Comment by 0xpatrickdev** [comment]
Tangential, I wonder if we should push more towards towards the docker website versus `brew --cask`. 

For the Mac CLI instructions, it seems we also need to include:
```sh
open -a Docker
```
after the brew command to actually open/start docker in the background.

@aj-agoric would you mind trying this? I'm not sure will be enough - Docker Desktop might present some add'l prompts to first time users. If you've already gotten past this part, I can set a new user on my computer to simulate a first time install.

**Comment by aj-agoric** [comment]
Hey guys, yes I tried the open -a Docker.. this launched a UI on my desktop that required me to fill out a few answers, accept terms, accept cookies, fill out a profile info... then it completed... I think this could close this issue, but yes we likely should add the "open -a Docker" to the flow before "docker hello world"

**Comment by aj-agoric** [comment]
can close this as the core issue works with above steps
