### ISSUE TITLE
Getting Started Tutorial Mac - Move X Code to Pre-requisite section.

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/documentation#1162]
Running through the tutorial with Mac, as is.. User experiences a long hang time with Yarn Install (20 mins +).. Reading the snippet that is there, its easy to decipher that we need to ensure Xcode is installed. If that is the case we sould not await the user to fail, then search through debugging notes, we should simply list Xcode as a requirement.  I Understand that most "developers" will have Xcode, however it may be helpful to think about "users" as well as "developers". 

Just thinking...

**Comment by Jovonni** [comment]
good point. its currently listed here:
https://docs.agoric.com/guides/getting-started/#installing-dapp-dependencies

The very last sentence in `installing Dapp Dependencies`:
```
On macOS, be sure to install [Xcode](https://apps.apple.com/us/app/xcode/id497799835).
```

should it be listed earlier in the flow @aj-agoric ?

**Comment by aj-agoric** [comment]
Either way I can go ahead and close this since the information is there.
