### ISSUE TITLE
Building `agd` Section is Unproductive/Useless

### ISSUE THREAD

**Issue by amessbee** [Agoric/documentation#1203]
There is **Building `agd`** section on [integration/chain-integration page](https://docs.agoric.com/guides/integration/chain-integration.html#building-agd) that points to [Getting Started](https://docs.agoric.com/guides/getting-started#build-the-cosmic-swingset-package) but there is no real information on building `agd` on any of these pages (or any other docs page?).
At the least, we can add something like this Ref: [SimplyStaking github](https://github.com/SimplyStaking/agoric-cl-setup-docs)
```sh
cd ~
node --version # 16.17.0 or higher
sudo npm install --global yarn
git clone https://github.com/agoric/agoric-sdk
cd agoric-sdk
git checkout 088b0abf214839326958b9c1109b2d50136636e4
yarn install
yarn build
yarn link-cli ~/bin/agoric
cd packages/cosmic-swingset && make
echo "export PATH=$PATH:$HOME/bin" >> ~/.profile
source ~/.profile
agoric --version
agd version
```

Ref: [packaging `agd` story](https://github.com/Agoric/agoric-sdk/issues/8033).

**Comment by dckc** [comment]
Pointing to [agoric-sdk software releases](https://github.com/Agoric/agoric-sdk/releases) is probably the best bet; that's what we do in [Syncing Up on Mainnet](https://docs.agoric.com/guides/getting-started/syncing-up.html#syncing-up-on-mainnet), since we actively maintain those releases.

In particular:

> node --version # 16.17.0 or higher

Node 16 is no longer LTS.

> sudo npm install --global yarn

`sudo npm install X` means "run any software from npm as root on my machine". I don't think we want to recommend that.

> git clone https://github.com/agoric/agoric-sdk
> cd agoric-sdk
> git checkout 088b0abf214839326958b9c1109b2d50136636e4

That's an Apr 2023 version.

**Comment by dckc** [comment]
## cosmic-swingset README could use some love

> cd packages/cosmic-swingset && make

That's one of the more relevant parts of the story. Ideally, we could give that as a short gloss and point people to the surrounding [@agoric/cosmic-swingset package docs](https://agoric-sdk.pages.dev/modules/_agoric_cosmic_swingset). But the README there documents a pixel demo from ~2018.

**Comment by dckc** [comment]
## Cosmos 0.45 -> 0.46

Speaking of the chain-integration page, it still talks about cosmos sdk 0.45 all over the place; for example:

> The Agoric Network currently uses cosmos-sdk v0.45.

But the current [Release agoric\-upgrade\-16 · Agoric/agoric\-sdk](https://github.com/Agoric/agoric-sdk/releases/tag/agoric-upgrade-16) notes

> cosmos-sdk v0.46.16

**Comment by dckc** [comment]
## Use install docs from inter bidding?

On [Bidding for Liquidated Collateral \| Inter Protocol User & System Docs](https://docs.inter.trade/user-how-to/bidding-for-liquidated-collateral) we have these instructions, which someone such as @otoole-brendan checks for each release:

```
git clone https://github.com/Agoric/agoric-sdk
cd agoric-sdk
SKIP_DOWNLOAD=false ./bin/agd build
export PATH=$PWD/bin:$PATH
```

That gets them whatever version of the code is on master at the time, which is a bit iffy.

@mhofman has suggested that we should recommend the `community-dev` branch for this sort of thing.

**Comment by mhofman** [comment]
> @mhofman has suggested that we should recommend the `community-dev` branch for this sort of thing.

This assumes `community-dev` gets updated as part of the release process, which it hasn't lately
