### ISSUE TITLE
Improve visibility of Orchestration 

### ISSUE THREAD

**Issue by mujahidkay** [Agoric/documentation#1222]
We want to improve the visibility of orchestration on our docs site to align with the release next week. Currently, it's well-hidden and doesn't even show up on the first fold of the page.

As per discussion at https://agoricopco.slack.com/archives/C03UF6JMWE7/p1727798397356379:

We will have a separate **Orchestrate** section on main page cards, navbar and sidebar. It's contents will be the same as we have for our Orchestration subsection under Learn and that subsection will be consequently removed. 

Main page card text detail: Build and manage multi-chain operations with the Orchestration API

Emoji: TBD

**Comment by toliaqat** [comment]
@mujahidkay did we have a discussion anywhere on renaming `Orchestration` to `Orchestrate`?

**Comment by mujahidkay** [comment]
> @mujahidkay did we have a discussion anywhere on renaming `Orchestration` to `Orchestrate`?

yes, in the slack thread of the issue description
