### ISSUE TITLE
getting-started/api.html shows 404

### ISSUE THREAD

**Issue by Jovonni** [Agoric/documentation#1224]
link shows 404: 
https://docs.agoric.com/guides/orchestration/getting-started/api.html

![image (4)](https://github.com/user-attachments/assets/343fc74e-e10d-49cb-8788-7929aac95c26)

May be related to changes here?
https://github.com/Agoric/documentation/pull/1223

**Comment by Jovonni** [comment]
Also I see that this link works:
https://docs.agoric.com/guides/orchestration/getting-started/key-concepts.html

Not sure what /api is supposed to point to, as we didn't have an API section for orch yet..

WDYT guys? @mujahidkay @amessbee

**Comment by mujahidkay** [comment]
It's a regression from https://github.com/Agoric/documentation/pull/1201
I'll fix this
