### ISSUE TITLE
I'm confused by the wording about `agoric start --no-restart`

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#159]
In the documentation in its current state https://agoric.com/documentation/getting-started/agoric-cli-guide.html#agoric-start : 

> Don't actually start the Agoric VM. 
> > `agoric start --no-restart`

Just from reading this, it's not clear to me what this command does and when it's supposed to be used

`agoric start` suggests that something not started will start

`--no-restart` suggests that something is already started and should not be restarted

The combinaison is confusing to me

> Don't **actually** start the Agoric VM. 

the **actually** suggests that the agoric vm won't be started, so i'm confused about using a command named `agoric start`

**Comment by katelynsills** [comment]
This is also confusing to me

**Comment by DavidBruant** [comment]
I investigated the code to understand what it does, reported back my exploration and tried to formulate a useufl question: https://github.com/Agoric/agoric-sdk/issues/979

**Comment by DavidBruant** [comment]
Per [mfig's comment](https://github.com/Agoric/agoric-sdk/issues/979#issuecomment-618449935), this option is not relevant any longer
I'm removing it from the documentation
