### ISSUE TITLE
Add "platform" to menu bar, write platform content

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#161]
- [x] Add Platform to menu bar
- [x] Write content about the Agoric Platform, including: SES, Cosmic-swingset, etc.
- [x] Reorder the menu bar to be: Zoe, ERTP, Platform

**Comment by DavidBruant** [comment]
>  Reorder the menu bar to be: Zoe, ERTP, Platform

Something about menu ordering has been itching me for a while, but i haven't been able to find a good solution

My current thinking is to list from left to right things that are from higher-level to lower-level, from more concrete to more abstract
So i'm proposing the following order:
- Getting started
- Guides
- Platform
- Zoe
- ERTP
- Glossary
- Learn more

**Comment by erights** [comment]
For the middle three, to go from higher-level to lower-level, should it be
   * Zoe
   * ERTP
   * Platform

?

**Comment by katelynsills** [comment]
Yeah, I agree with @erights. It should be in the order of the stack, either going up the stack or down the stack. I like down the stack as Mark has it:

- Getting started
- Guides
- Zoe
- ERTP
- Platform
- Glossary
- Learn more

**Comment by katelynsills** [comment]
Closed by #162

**Comment by DavidBruant** [comment]
yes, good catch @erights 
and thanks @katelynsills for making the change!
