### ISSUE TITLE
Uniformize Swingset capitalisation

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#163]
> In the top diagram, it's "SwingSet". Here, it's "Swingset". Pretty sure I recall seeing "SwingSet" other places as well. Should decide on a consistent capitalization.

_Originally posted by @tyg in https://github.com/Agoric/documentation/pull/162_

**Comment by erights** [comment]
FWIW, the actual source https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet also says "SwingSet"

**Comment by tyg** [comment]
Fixed in PR 397
