### ISSUE TITLE
Document what's available for deploy scripts in "referencesPromise"

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#165]
I'm talking about what's here:

https://github.com/Agoric/dapp-encouragement/blob/bfc928e2c867bc1ba090993cb1cec7bfcf1bfe4f/contract/deploy.js#L20-L45

I have found this: 

https://github.com/Agoric/agoric-sdk/blob/7fa8c7969bb2e8fffd661e28e227c37de031b32f/packages/cosmic-swingset/lib/ag-solo/vats/bootstrap.js#L108-L116

Is this the object that is available to all deploy scripts being sent via `agoric deploy`?

ping @michaelfig @Chris-Hibbert

**Comment by michaelfig** [comment]
Yes, it is the `home` object available in the REPL.

**Comment by Chris-Hibbert** [comment]
Here's a write-up that I did earlier of the sharing service when it was called the handoff service. I think I've fixed all the names so they match the current API.

==
home.handoffService is a handoff service that lets you connect to other vats that are connected to the same remote vat. handoffService has three methods: createBoard(name), grabBoard(name), and validate(board). These allow you to create a 'corkboard' which you can use to pass items to and from another vat. The handoff service's methods are designed to allow you to share a newly created corkboard with one other vat, after which the name can't be reused.

The way to use it is to call createBoard() with a name that you share with someone else. They then call grabBoard() and pass the name you gave. If they get a valid corkboard, then you have a private channel. If they don't get it, then someone else must have tried to grab the name first, and you can discard that one and try again.

Once you each have an end, either of you can call addEntry(key, value) to store an object, which the other party can retrieve with lookup(key).

**Comment by tyg** [comment]
Transferred information into REPL doc draft.

**Comment by Chris-Hibbert** [comment]
When closing an issue because it's been included in another, it's helpful to include a link to the new issue.

**Comment by tyg** [comment]
Incorporated into REPL docs in [PR 411](https://github.com/Agoric/documentation/pull/411) and merged in. Closing issue.
