### ISSUE TITLE
Note on deploy scripts, issuers, Zoe/vat spawner

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#171]
copy/pasting what @katelynsills wrote elsewhere:

> The deploy scripts are ephemeral, so any object that is created in the deploy script will die as soon as the deploy script stops, unless it is put somewhere long-lasting, like in the registry
So, you should probably not use the deploy script for making an issuer unless you put all of the issuer-related things on-chain somewhere, which is not very straightforward right now
We're in the middle of revamping an alternative to Zoe, which we call the spawner, which would let you put JS code running persistently on-chain
Until we have that available for general use, the best thing to do is use Zoe to create running contracts that mint payments.
(...) in most cases, a mint would be in a separate contract, and a Zoe contract is used only for making offers using things that have been minted somewhere else

**Comment by tyg** [comment]
Done in [PR #425](https://github.com/Agoric/documentation/pull/425)
