### ISSUE TITLE
[ERTP] Change ERTP tutorials to be within Zoe contracts

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#173]
Many of our ERTP tutorials and API snippets do things that you wouldn't necessarily do in a Zoe contract. We should rewrite the ERTP docs so that they make sense in the context of Zoe.

**Comment by tyg** [comment]
Since we've rewritten all the ERTP docs with Kate's approval, I'll assume they now sync up with Zoe.

**Comment by katelynsills** [comment]
Hey @tyg, can we leave this open? It's a conceptual step that I don't think we've fully thought through or resolved.

**Comment by erights** [comment]
@katelynsills @tyg can I give this to the two of you? Can this be closed?

**Comment by katelynsills** [comment]
Yup, feel free to assign it to me. I think there is still work to be done here in terms of thinking of where we explain `makeIssuerKit` given that dapp and contract developer will likely not use it directly.

**Comment by Tyrosine22** [comment]
This task is either stale or already resolved, depending on how you look at it.
