### ISSUE TITLE
Blog post on Use vs. Mention in ERTP 

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#176]
Explain the distinction that ERTP allows us to make between sending valuables and talking about their value.

Which objects to we each need access to in order to exchange a dollar?
Which objects do we need in order to negotiate the dollar price of some other good?

**Comment by tyg** [comment]
As we've included warnings at length in the docs about not confusing amount objects with actual assets, and how payments are the actual assets being sent and amounts are just a description, I think this one's been done.

**Comment by Chris-Hibbert** [comment]
The blog post hasn't been abandoned.

**Comment by katelynsills** [comment]
@Chris-Hibbert Was this the medium post? can this be closed?

**Comment by Chris-Hibbert** [comment]
Yep.  It's done now.

https://agoric.com/blog/technology/the-settlers-of-blockchain/
