### ISSUE TITLE
Questionning Github Pull Requests for first draft documentation

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#18]
> (...) lots of back and forth. I wonder whether a github pull request is a good tool for this

_Originally posted in https://github.com/Agoric/Documentation/pull/10#issuecomment-537056291_ 

It's not the first time i've come across this problem. A git/hub repo with markdown resources is cool for historicity, receiving pull requests for small changes, and easy publishing, but for a first draft with potentially lots of discussion, it seems inappropriate

Among other experiences, i've had this problem with a collective blog
One solution we came up with is to use Google Docs for the first draft, then transform to markdown when we're in agreement
As long as we don't create dozens of new pages a week, the cost of transforming manually a google docs to markdown is fairly small. It's also possible to automate this transformation (i started a [project for this purpose](https://github.com/ClementineHahn/PerryWhite) with a friend as a concrete exercice for her to learn how to code) and turn the process from Google Docs to Pull Request on the proper repo into 1 click

**Comment by tyg** [comment]
It's ended up as writer's choice.
