### ISSUE TITLE
In AtomicSwap contract, "Asset" and "Price" keywords suggest an asymetry that does not exist

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#180]
I feel like "Asset" implicitely refers to a non-fungible token while it doesn't, it could be any ERTP asset
Symetrically, "Price" seems like it's a fungible token while it can be any ERTP asset as well

My understanding is that the contract is fully symetric. The person with the first invite can place the `Asset` or the `Price` to their choosing

As a consequence, i feel like the different names confusingly convey an asymetry that does not exist

**Comment by Chris-Hibbert** [comment]
I think the names were partly chosen to express two roles in a purchase transaction. Conventionally we think of one good as the thing being purchased and the other as the unit of account (i.e. the denominator in the transaction). It's harder to come up with two distinct names when you think  of a barter transaction (which is maybe closer to the nature of a "swap".) 

Some people may be happy with calling the two keywords "goodA" and "good", but that seems less clear to me. Even when we're trading gold bullion for bitcoins, and both are just as good denominators.  Or a painting for a month's rent on an apartment, where both are equally bad denominators. 

Even when the two parties might have different theories about how they represent the price of the transaction, I'm still happier calling one Price and the other Asset, regardless of whether they match my particular intention or bookkeeping practices.

**Comment by katelynsills** [comment]
I agree with Chris.

**Comment by tyg** [comment]
Chris' comment and Kate's agreement should resolve this issue.
