### ISSUE TITLE
Write Debugging doc

### ISSUE THREAD

**Issue by tyg** [Agoric/documentation#183]

**Comment by tyg** [comment]
From #173 (closed due to merging here):

chip commented:
I've already verified that you can add breakpoints and step through random vat code running in swingset runner. Are there additional complications/restriction w.r.t Zoe that need to be taken into account?

katelynsills commented:
I think Dean was thinking that with your recent verification, you and Tom would be the best to write up instructions on how to go about adding breakpoints and stepping through random vat code / contract code. I don't think we have anything like that on agoric.com/documentation yet.

**Comment by dckc** [comment]
We're tracking this as #963 now.
