### ISSUE TITLE
Find existing documentation in *.rst format and decide what to do with it

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#19]
> I notice that some of our own documentation is *.rst rather than *.md . Should we suggest that contributions can/should be *.rst ? How do we decide when to use which?

_Originally posted by @erights in https://github.com/Agoric/Documentation/pull/11_

Depending on the case, it can be transformed to .md or kept as is. We can see when the case comes

**Comment by tyg** [comment]
I'd say erights comment decides the issue. And all new docs seem to be in .md
