### ISSUE TITLE
Licence for non-code content

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/Documentation#2]
The current licence is Apache-2
However, it's not clear whether this licence appropriately addresses non-code contents (prose and images)

- [MDN](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses) addresses this with code having a CC-0 licence and content having CC-BY-SA licence
- [developers.google.com](https://developers.google.com/terms/site-policies) has its code in Apache 2 and content as CC-BY

**Comment by Chris-Hibbert** [comment]
While Apache may not be primarily aimed at prose, it seems to cover the main points we need to handle. It explicitly says it covers documentation, and the limitations and grants don't restrict their applicability to code. It authorizes use (including private and commercial), modification, distribution, and sharing. Warranties and patents are irrelevant. 

Using a consistent license is probably more important than any changes we'd want to make.

**Comment by DavidBruant** [comment]
ok, sounds good, thanks!
