### ISSUE TITLE
glossary: AllegedName, AmountMath lack citations; ERTP link is odd

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#202]
Glossary entries such as [Payment](https://agoric.com/documentation/glossary/#payment) work well: a short gloss followed by a link to authoritative documentation.

AllegedName, AmountMath lack links, as if the glossary defines these terms, when in fact they are defined in an API.

The ERTP entry links to an Crockford on OCaps; why not [Electronic Rights Transfer Protocol \- ERTP \| Documentation](https://agoric.com/documentation/ertp/guide/#introduction)?

Object Capabilities seems like it should have its authoritative documentation in something like [Distributed programming in JavaScript \| Documentation](https://agoric.com/documentation/distributed-programming.html). Then the entry could be shorter.

**Comment by tyg** [comment]
Glossary has been updated.
