### ISSUE TITLE
struggling to build mental model of deploying contracts in the Agoric SDK

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#205]
I started reading [Deploying Smart Contracts](https://agoric.com/documentation/getting-started/deploying.html); when I get to:

> Deploy and setup an application program to the local server

What does "the local server" refer to? No fair using definite descriptions ("the ...") before introducing the referent.

> All deployment happens via the local running Agoric process (specifically, the ag-solo process)

Is "the local running Agoric / ag-solo process" the same as "the local server"? If so, use the same term, please.

In [Starting a Project](https://agoric.com/documentation/getting-started/start-a-project.html) I find:

> Start the Agoric VM.

Is that the same thing or something else?

> Its registry key is written to a config file in the ui directory.

Which ui directory? Another unbound definite description.

> Bundle the api code and deploy it to the running "api" process (e.g., the local ag-solo process)

Now the ag-solo process is called the api process? (with "api" in quotes?)

> that communicates with either a locally running or remote chain.

So there's always a chain? I didn't see one in Starting a Project. Did I miss it?

> The local process has ...

Now it's the "local process"? I think this is the 6th term so far, if my understanding is correct, i.e. that these all refer to the same thing. (Maybe I lost count.)

> and the application user's wallet.

Which application user? (another unbound definite description). There's always exactly one user?

> The deploy.js scripts run in an ephemeral Node.js outside of the Swingset kernel. 

Is "the Swingset kernel" a 7th name for the same thing?

> The spawner runs within ag-solo

Which spawner? (another unbound definite description). Suggest: "ag-solo includes a spawner ...".

I eventually found [Agoric's Cosmic SwingSet](https://agoric.com/documentation/manual-setup/) which seems to cover much of the same material, though some parts of it seem out of date. Please do use figures like the ones there, though; they help a lot!

**Comment by dtribble** [comment]
I'll answer questions here, and we can then figure out what to update in the doc.
> > Deploy and setup an application program to the local server
> What does "the local server" refer to? No fair using definite descriptions ("the ...") before introducing the referent.

The "local server" is the api server (currently a node process) running on behalf of the user. In development, it's typically the process launched with `agoric start`, which effectively includes an api server and a fake chain implementation for local debugging.  

If you are running with local or test chain, then it's the api server (the `ag-solo` process) which has the user's keys, runs on the user's machines, and connects to the chain via IBC-like protocols. You don't need to worry about this until you are deploying processes in more complicated configurations.

> > All deployment happens via the local running Agoric process (specifically, the ag-solo process)
> Is "the local running Agoric / ag-solo process" the same as "the local server"? If so, use the same term, please.

OK

**Comment by dckc** [comment]
> ... If you are running with local or test chain, then it's the api server (the `ag-solo` process) which has the user's keys, runs on the user's machines, and connects to the chain via IBC-like protocols. You don't need to worry about this until you are deploying processes in more complicated configurations.

The more complicated configurations are exactly what I expect to see discussed in "Deploying Smart Contracts", since the "just follow the directions; don't think too hard" stuff is covered in "Start a Project".

In particular, I'm trying to figure out how to deploy to testnet.

**Comment by dtribble** [comment]
> > Start the Agoric VM.
> 
> Is that the same thing or something else?

Same thing as "local server process". Clearly too many names. This arises because you can get the local server process in various ways, but it always fulfills the same role. It's enlightening to see all these juxtaposed. We will name the role of that process. 

As a fallback, I will call it the `ag-solo` for now, where `agoric start` may launch an `ag-solo` with an attached fake chain for ease of debugging.
 
> > Its registry key is written to a config file in the ui directory.
> 
> Which ui directory? Another unbound definite description.

The UI directory sitting in the very same directory you ran deploy from. Is that not straightforward?

> > Bundle the api code and deploy it to the running "api" process (e.g., the local ag-solo process)
> 
> Now the ag-solo process is called the api process? (with "api" in quotes?)

Yes. As a developer/deployer of an application, the "user" is really the application user, so that user's a`-ag-solo` is the api server for the application. Definitely needs some clarification. When I'm developing the "zot" application, the default user is the "zot" application user, not "dean", and so the wallet and purses and `ag-solo` are for the application.

> > that communicates with either a locally running or remote chain.
> 
> So there's always a chain? I didn't see one in Starting a Project. Did I miss it?

It's a "fake" chain running in the same processes as the `ag-solo` so make debugging easier. You can also run in "separate local chain mode", but we need to document how.

> > The local process has ...
> 
> Now it's the "local process"? I think this is the 6th term so far, if my understanding is correct, i.e. that these all refer to the same thing. (Maybe I lost count.)

You are correct, though they loosely refer to either `ag-solo` or `ag-solo + fake-chain`.

**Comment by dckc** [comment]
...
> > Which ui directory? Another unbound definite description.
> 
> The UI directory sitting in the very same directory you ran deploy from. Is that not straightforward?

When I hit "the ui directory" I went back to the top of the document to see what context I might have missed. The introductory sentence is:

> The deploy command in the [agoric command line tool](https://agoric.com/documentation/getting-started/agoric-cli-guide.html#agoric-deploy) supports deploying contracts ...

So I looked at the agoric command line tool docs for a ui directory. No joy.

If this document assumes "Starting a Project" as context, it's not too hard to make that more clear: start with "Recall from [starting a project](#) that each Agoric SDK project has a `contract` directory, a `ui` directory, and an `app` directory." or some such. Then "the ui directory" has a clear referent.

This goes back to [Making links into context](https://www.w3.org/Provider/Style/IntoContext.html) in the original [Style Guide for Online Hypertext](https://www.w3.org/Provider/Style/): "you can't rely on your reader having followed your path through your work."

**Comment by dtribble** [comment]
> >and the application user's wallet.
> 
> Which application user? (another unbound definite description). There's always exactly one user?

The user account for the application, e.g., "zot app user" above, who is the party that is building and deploying the application, and running an `ag-solo` with the private keys of the application.

> > The deploy.js scripts run in an ephemeral Node.js outside of the Swingset kernel.
> 
> Is "the Swingset kernel" a 7th name for the same thing?

This is more an internal technical detail, but is close enough to another use to need to change.  I think the important thing is that the deploy script is just running as a standalone JS program in node. (It may then bundle stuff to be run in the `ag-solo` to do various tasks on-chain).
 
> > The spawner runs within ag-solo
> 
> Which spawner? (another unbound definite description). Suggest: "ag-solo includes a spawner ...".

Agreed. Hmm. That word should be in the glossary. Will get it added. 

> I eventually found [Agoric's Cosmic SwingSet](https://agoric.com/documentation/manual-setup/) which seems to cover much of the same material, though some parts of it seem out of date. Please do use figures like the ones there, though; they help a lot!

Agreed. Yes it's the original that supports many other running scenarios. Those diagrams are new! Will appropriate them :)

**Comment by dckc** [comment]
experimenting a bit...

```mermaid
C4Component
    title Agoric Sim Chain and Solo Client

%% https://plantuml-stdlib.github.io/C4-PlantUML/#component-diagram
%% Container(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
%% Component(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
%% Rel(from, to, label, ?techn, ?descr, ?sprite, ?tags, ?link)
%% BiRel

    Container(ag-solo, "Solo Client", "node.js, XS", "solo, aka non-replicated,<br>Hardened JS service")
    Container(sim-chain, "Sim Chain", "node.js, XS", "simulation of replicated<br>Hardened JS blockchain")

    BiRel(ag-solo, sim-chain, "Msg")
```
