### ISSUE TITLE
Minor mistake in installation instructions

### ISSUE THREAD

**Issue by FUDCo** [Agoric/documentation#206]
(Actually, I'm not entirely sure if this is a documentation problem or an issue with the installer software itself, but I'll treat it as a doc issue for now as it will lead to doc changes however it's dealt with).

Step 9 of https://agoric.com/documentation/getting-started/before-using-agoric.html says "Select a directory to install the Agoric CLI in. For example, `yarn link-cli ~/bin/agoric`"  However, the thing you are specifying is not actually a directory name but the name of the Agoric CLI utility itself.  I was thinking I wanted to put it in my `bin` directory, so I typed `yarn link-cli ~/bin` and it failed with the complaint that the directory `/Users/chip/bin` already existed.  So I tried again specifying `~/bin/agoric` and that created an `agoric` file in my `bin` directory; that file is a shell script, not a directory.

Either the doc should be changed to tell you to name the file for your Agoric CLI utility or the `yarn` script should treat the command line arg as the name of the directory to put `agoric` into.  (Actually, I'd argue for the latter rather than just changing the doc because it makes a lot more sense and having the name of the utility be standardized will make the other docs more straightforward.  Though if we do that the doc will _still_ need to be changed to have the example not suggest `~/bin/agoric` but rather just `~/bin`, which does make more sense.

**Comment by michaelfig** [comment]
The doc should be updated.

If we choose to break compatibility with the existing command in the future, we should change its name, too, to avoid confusion.
