### ISSUE TITLE
Rewrite/enhance Zoe Guide

### ISSUE THREAD

**Issue by tyg** [Agoric/documentation#214]
Emphasis on howto/cookbook, incorporate usage and design advice, APIs and helpers. Tie in with contract design doc.

**Comment by katelynsills** [comment]
I agree with the above. I think when we rewrite the Zoe guide we should start thinking about commonly desired user tasks like:
* minting my own tokens/digital assets and sending them to a friend
* receiving digital assets from a friend
* Making, testing, and deploying a new contract installation
* Making a new instance of an AMM and collecting fees/gains from that instance

I think this means that the Zoe guide is really an Agoric platform guide, including the wallet and dapp deployment. It might be possible for the Zoe guide to go back to being more narrowly focused on Zoe after we have more tutorials that cover the above questions instead.

**Comment by Tyrosine22** [comment]
This task has some good ideas for future doc tasks.

**Comment by dckc** [comment]
https://docs.agoric.com/guides/zoe/ is much more how-to now
