### ISSUE TITLE
VuePress `<router-link>` doesn't produce shareable links

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#255]
**Describe the bug**

The links produced by VuePress (or maybe more precisely, the pages containing anchors) work if you click on them, but not if you copy-paste or open-in-a-new-tab.

**To Reproduce**

Coming soon, there will be a "Related Methods" section [here](https://agoric.com/documentation/ertp/api/payment.html).

If you click on one of the links, it'll take you to the referenced section, scrolling to the appropriate part fo the page.

If you copy the link, or Command-click, or open-link-in-new-tab, or copy the URL after clicking, you end up with a link that takes you to the top of the page.

**Expected behavior**
links with #anchors should take you to the anchor on the destination page. Links that are visible should be shareable, and should go to the right place.

**Platform Environment**
 - what OS are you using? Mac
 - Using a recently updated vuePress
 - I was running this on a local vuePress server to review doc changes

**Comment by tyg** [comment]
Closing issue since we're going to go with relative links in Markdown instead. Among other things, the link checker doesn't work on <router-link>s but does work on links in Markdown.

**Comment by katelynsills** [comment]
I think that the Markdown style links become router-links and that the problem might still remain. We should test it out.
