### ISSUE TITLE
Update documentation for changes to `zcfSeat.kickOut`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#259]
zcfSeat.kickOut no longer throws as of https://github.com/Agoric/agoric-sdk/pull/1663.

We should update the documentation to match.

**Comment by katelynsills** [comment]
I had forgotten that the `zcfSeat` docs are still in the works, so there is not yet anything to change. Reassigning to @tyg to consider when writing up the `kickOut` method.

**Comment by tyg** [comment]
Done.
