### ISSUE TITLE
Document Assert/Logging API

### ISSUE THREAD

**Issue by tyg** [Agoric/documentation#267]

**Comment by tyg** [comment]
From the now closed #230: Documentation on `@agoric/assert` including q() #230

katelynsills commented on Jul 6
I think a new feature q() got added, but it hasn't been explained to users in any documentation that I'm aware of.

**Comment by tyg** [comment]
From the now closed #74: Document 'Assert' package compared to Node's `assert` #74

**Comment by Tyrosine22** [comment]
I have no idea what's going on with this bug. The title suggests one thing, while one comment suggests something else entirely, and another comment suggests a third issue. I'm going to close this bug. If any of these issues prove important, I can always open a new bug.
