### ISSUE TITLE
links in docs open new windows even when not leaving the site

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#296]
for example, on https://agoric.com/documentation/getting-started/ , when I follow the "Before Using the Agoric SDK" link, I get a new tab. Each link I follow gives me a new tab. I'd expect a normal link where I can use the back button and such.

**Comment by katelynsills** [comment]
Yup, this occurs when we don't use relative links. @tyg can we fix?

**Comment by tyg** [comment]
Working on it; mostly cleaned up Getting Started, but there are four links I'm not sure if they can be converted to relative as they're not in the agoric/documentation repo;

https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/networking.md

https://agoric.com/papers/

https://github.com/Agoric/   

https://agoric.com

Any suggestions?

**Comment by dckc** [comment]
when leaving the docs structure, it wouldn't be so jarring to have a new tab open
