### ISSUE TITLE
Make use of code snippet imports

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#305]
Vuepress [allows for code snippets to be imported](https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets). We should take advantage of this to be able to have the code snippets in a separate folder and potentially run tests against them.

**Comment by Chris-Hibbert** [comment]
I would think it would make sense to grab examples from live code when that serves the purpose, and creating new code for a writing sample would be second choice. In the former case it's already known to compile, pass lint, and be useful. We should be able to set it up so other code samples get linted, but more testing than that would be hard.

**Comment by katelynsills** [comment]
Closing this in favor of the more targeted plan now that we have a working example in the Zoe Intro: https://github.com/Agoric/documentation/issues/335
