### ISSUE TITLE
Setup Algolia DocSearch safely (using SES?)

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#325]
They've crawled our site, and we just need to add some specified JavaScript to the site (see below). However, as @warner pointed out, we should be cautious about adding external scripts to the site. 

We should investigate what is necessary to make this safe, and if SES might be a good solution. 

-----
### Email Contents from Algolia DocSearch
Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: 'f292dc8bd4dce033ed7a4ddfbb87bdb8',
indexName: 'agoric',
inputSelector: '### REPLACE ME ####',
algoliaOptions: { 'facetFilters': ["lang:$LANG"] },
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet
to a CSS selector that targets your search input field.

- Replace $LANG with the lang you want to search on.
The list of possible lang is hardcoded in the config.
So as of today you have: en-US

For example if you want to refine the search to the lang "en-US" just specify: 'facetFilters': ["lang:en-US"]

- Optionally customize the look and feel by following the DocSearch documentation
(See https://docsearch.algolia.com/docs/styling/)
- You can also check your configuration in our GitHub repository
(See https://github.com/algolia/docsearch-configs/blob/master/configs/agoric.json).

(see Kate for the full email)

**Comment by Tyrosine22** [comment]
This appears to be thoroughly outdated.
