### ISSUE TITLE
Fix description of zcf.getTerms() in ZCF API to include `maths`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#343]
The [documentation for `zcf.getTerms()`](https://agoric.com/documentation/zoe/api/zoe-contract-facet.html#zcf-getterms) doesn't clearly state what is returned from `zcf.getTerms()`. It should be:

```
{ brands, issuers, maths, customTermA, customTermB ... }
```

where brands, issuers, and maths are all keywordRecords, like:

```
{
    brands: { A: moolaKit.brand, B: simoleanKit.brand },
    issuers: { A: moolaKit.issuer, B: simoleanKit.issuer },
    maths: { A: moolaKit.amountMath, B: simoleanKit.amountMath },
    whatever: 'whatever',
 };
```

**Comment by tyg** [comment]
Fixed in PR 400
