### ISSUE TITLE
improve documentation of example Zoe Contracts

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#345]
Some of the Zoe contracts are described on [the documentation site](https://agoric.com/documentation/zoe/guide/contracts).

 * [x] The contract code should include a cross reference to the write-up
 * [x] The contracts should have header comments explaining the proposals they  expect (some already do.)
 * [ ]  All the contracts should have descriptions and be listed on the web page. They are missing for:
   * [x] automaticRefund
   * [x] mintAndSellNFTs
   * [x] mintPayments
   * [x] otcDesk
   * [x] sellItems
   * [x] useObjExample (packages/zoe/test/unitTests/contracts/)
   * [x] escrowToVote (packages/zoe/test/unitTests/contracts/)

**Comment by katelynsills** [comment]
I'm going to create a new issue for what documentation requirements remain, and will close this when that's up.

**Comment by Chris-Hibbert** [comment]
Seems good. I've looked at this several times and wanted to close it, but it's so open ended that there's always work left to do.

**Comment by katelynsills** [comment]
Closing and opening issue https://github.com/Agoric/documentation/issues/403 instead for further work
