### ISSUE TITLE
Document Chain deployment environment/REPL

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#358]
There's some internal documentation on the initial endowments in `home` here:
https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/README.md#initial-endowments

I think we should have developer-facing documentation of all the functionality available in `home`. The objects in home should be cross-checked against those that appear in `home` when the REPL is brought up.

**Comment by Chris-Hibbert** [comment]
I just answered another question in discord support about timer service. Each time I refer to this internal doc: https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/TimerService.md

**Comment by tyg** [comment]
REPL docs are in Github now
