### ISSUE TITLE
Markdown links not rendering on documentation home page

### ISSUE THREAD

**Issue by barbaraliau** [Agoric/documentation#393]
"Learn about [ERTP](/ertp/guide/), a uniform way of transferring tokens and other digital assets in JavaScript."
"Ready for more? Check out [Zoe](/zoe/guide/)."

![Screen Shot 2020-11-24 at 12 26 49 PM](https://user-images.githubusercontent.com/10275927/100141994-72031c80-2e50-11eb-8476-9d29401519e7.png)

**Comment by katelynsills** [comment]
Many thanks for the bug report @barbaraliau!
