### ISSUE TITLE
Write an introduction to Smart Contracts

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#4]
- blockchain
- solo node
- (Vat/SwingSet ?)
- ERTP/Contract host
    - contract source code (+Jessie)
    - terms and inviteMaker arguments
    - [provided top-level variables](https://github.com/Agoric/ERTP/blob/8f42af53581821bb16a9f4e3d62603833354ef8b/core/contractHost.js#L53-L63)

**Comment by erights** [comment]
The provided top-level variables list is a kludge (note the "todo" comment), waiting for integration with our support for es-modules. Once that happens, most of these will be replaced by import statements in the modules themselves.

**Comment by DavidBruant** [comment]
> Once that happens, most of these will be replaced by import statements in the modules themselves.

ok, good to know, thanks!
I feel this only shifts what needs to be documented: instead of top-level variable names available to contracts, it will be available import names available to contracts
So i guess most of th work documenting the top-level variables will be useful after the switch to modules

> waiting for integration with our support for es-modules

Do you have a idea (even if just a rough one) of when this will happen? 1/3/6/12/24/+ months?

**Comment by erights** [comment]
> So i guess most of th work documenting the top-level variables will be useful after the switch to modules

Yes.

> Do you have a idea (even if just a rough one) of when this will happen? 1/3/6/12/24/+ months?

Attn @dtribble @michaelfig We should discuss how the actual dedicated time still needed translates into calendar time.

**Comment by katelynsills** [comment]
Closing as outdated
