### ISSUE TITLE
Flesh out contract documentation by adding code snippets

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#403]
- [ ] PriceAuthority - could use snippets of actual usage even though this is not a contract per se
- [ ] OTC Desk 
- [ ] Sell Items
- [ ] Barter Exchange
- [ ] Escrow To Vote
- [ ] Mint Payments
- [ ] Mint and Sell NFTs
- [ ] Use Obj Example
- [ ] Automatic Refund

**Comment by Tyrosine22** [comment]
Between the improved/revised API docs & standardizing (and expanding) the contract docs per bug #222, I'm not sure that this work item is worthwhile.
