### ISSUE TITLE
ERTP Purse API documentation is missing methods

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#405]
The current purse methods are:

<img width="466" alt="Screen Shot 2020-12-09 at 1 40 39 PM" src="https://user-images.githubusercontent.com/2441069/101691850-26419d00-3a24-11eb-8e4f-89e8f28da3ad.png">

But the documentation has:

<img width="301" alt="Screen Shot 2020-12-09 at 1 41 24 PM" src="https://user-images.githubusercontent.com/2441069/101691905-3f4a4e00-3a24-11eb-8eef-3bfd640c7a20.png">

**Comment by Chris-Hibbert** [comment]
While someone is looking, I noticed that the release version listed is `Zoe Alpha Release v0.8.1. Last updated 2020-9-15.` The package.json has `0.10.0`. What the most current version we've published?

**Comment by katelynsills** [comment]
> While someone is looking, I noticed that the release version listed is `Zoe Alpha Release v0.8.1. Last updated 2020-9-15.` The package.json has `0.10.0`. What the most current version we've published?

Good eye, it is 0.10.0. https://www.npmjs.com/package/@agoric/zoe
