### ISSUE TITLE
Responsive header on documentation site hides logo inappropriately

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#412]
When visiting the documentation site, with a browser window between 900 and 1250 pixels wide, the nav menu at the top of the screen slides left to progressively cover up the Agoric logo. In the middle of that range, you only see half the logo. There's some dynamic trading off being done at different widths that sometimes hide the search bar, and sometimes slide it off screen. I think a different trade-off that left the logo, progressively shrank the search box, and found a different arrangement of the top menu at narrow widths would be better. Actually on mobile at very narrow widths (< 700 pixels), it switches to a hamburger menu, which works well.  But between 700 and 900 it's not great.

![image](https://user-images.githubusercontent.com/13372636/103232994-c8042d80-48f0-11eb-819e-4176353d1759.png)

**Comment by tatyana0219** [comment]
Vuepress doesn't seem to have a setting to change when the hamburger appears, so will have to try bringing in the hamburger at a wider layout with CSS.

I can't see "Hackathon" anywhere in the code, after pulling from master. Was the site on the master branch?

**Comment by Chris-Hibbert** [comment]
> I can't see "Hackathon" anywhere in the code, after pulling from master. Was the site on the master branch?

I opened to a [random link from my history ](https://agoric.com/documentation/zoe/api/zoe.html#e-zoe-getbrands-instance) and see hackathon. in the top nav.  actually as I browse around, it's in all the headers.

When I grep the sources, I see lots of occurrences of "Hackathon" under `main/.vuepress/dist`, and also in `main.vuepress/config.js and main/.vuepress/themeConfig/nav.js`

**Comment by tatyana0219** [comment]
I don't see it in either of those files for me. I have git pulled the latest from master but it's not there. Perhaps the server is on another branch?

**Comment by katelynsills** [comment]
@tatyana0219 try `main` instead. We changed from `master` to `main`

**Comment by tyg** [comment]
Closed with [PR 417 ](https://github.com/Agoric/documentation/pull/417)
