### ISSUE TITLE
Source doc for ses-standalone gone

### ISSUE THREAD

**Issue by erights** [Agoric/documentation#415]
Web searching for this page I found https://ses-secure-ecmascript.readthedocs.io/en/stable/draft-standalone-spec.html . But I cannot find a source document for it in any of our repositories. I don't know where to file this bug, but the natural home for this page is either https://github.com/tc39/proposal-ses/blob/master/refactor-spec-approach.md or https://github.com/Agoric/SES-shim . Or, has this doc been obsoleted by some other doc? Which would be great!

Attn @kriskowal @dckc

**Comment by dckc** [comment]
The readthedocs page bears rev fdb393f8 , which seems to be available as https://github.com/Agoric/SES/commit/fdb393f8

so...
https://github.com/Agoric/SES/blob/fdb393f817f6124c4d055bff26b68e4cbe17618e/docs/source/draft-standalone-spec.rst

**Comment by dckc** [comment]
seems to have survived as
https://github.com/Agoric/SES-shim/blob/master/packages/ses/docs/source/draft-standalone-spec.rst
