### ISSUE TITLE
Document Agoric structures and process flows

### ISSUE THREAD

**Issue by tyg** [Agoric/documentation#421]
Write a document that explains and illustrates via diagrams and flow charts how the various Agoric system components (Dapps, ag-solos, Agoric CLI commands, etc.) interact and function, as well as overall composition.

**Comment by Tyrosine22** [comment]
Related bug: #756

**Comment by Tyrosine22** [comment]
I'll take care of this item when I write the Agoric Overview topic.

**Comment by dckc** [comment]
too broad to track
