### ISSUE TITLE
Reorganize Documentation repo folders and files

### ISSUE THREAD

**Issue by tyg** [Agoric/documentation#447]
Prior to release, we should fix the disorganization of the Documentation repo caused by files being added at top-level instead of an appropriate folder and doc files growing due to being used for more than one purpose (e.g. the Wallet doc covers usage, the UI, and the API). 

Folder-level reorg
- [x] Create `guides` folder under `main/`
- [x] Move chainlink-integration.md under /guides/
- [x] Move distributed-programming.md under /guides/
- [x] Move wallet-api.md under /guides/
- [x] Move assets under /guides
- [x] Delete in-progress.md file [empty, not used since 2019 creation]
- [x] Rename REPL/ to repl/
- [x] Move (or copy) Dynamic IBC doc from agoric-sdk repo to under /guides, leave redirect statement in sdk repo 
- [x] Create overall /guides/ sidebar.
- [x] Add redirects on old URLs to new ones.
- [x] Fix internal document links to the moved/renamed files/folders
- [x] Fix menubar and sidebar links to the moved/renamed files/folders.

File level reorg
- [x] Create /wallet folder, split doc into Guide, UI, API docs under it.
- [x] Create /javascript-modifications folder, split JS distributed programming into files under it, add SES related files under it. 
- [x] Determine if chainlink-integration file should be deleted, kept, merged with another doc, enhanced.
- [x] Create Agoric CLI folder, split doc into CLI reference and multiuser Dapps files under it.
- [x] Move PriceAuthority API reference from Zoe Guide to new file/section under Zoe API (i.e. Zoe, ZCF, Helpers, and Price Authority API references)
- [x] Add item/link to Learn More menu to point at our YouTube channel
- [x] Any papers worth adding to our Papers page?
- [x] Add redirects on old URLs to new ones.
- [x] Write up how to do redirects and add to .CONTRIBUTING.md
- [x] Fix internal document links to the moved/renamed files/folders
- [x] Fix menubar and sidebar links to the moved/renamed files/folders.

Link level changes
- [x] Change /wallet-api.md to /guides/wallet/ and /guides/wallet/api.md
- [x] Change /REPL/ to /repl/
- [x] Change /chainlink-integration.md to /guides/chainlink-integration.md
- [x] Change /zoe/guide/price-authority.md to /zoe/api/price-authority.md
- [x] Check assets links to be sure still work.
- [x] Change /distributed-programming.md to /guides/js-programming/  and any specific section pointers to the right file.
- [x] Change /getting-started/agoric-cli-guide.md to /guides/agoric-cli/ and any specific section pointers to the right file

**Comment by katelynsills** [comment]
This looks right to me!

**Comment by katelynsills** [comment]
One thing - `javascript-modifications` seems long and unappealing to the public. How about just `js`?
