### ISSUE TITLE
I don't understand the insist function of assay.getUnitOps()

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#46]
https://github.com/Agoric/Documentation/blob/master/main/ertp/api/assay.md#assaygetunitops

```js
function insist(asset, units) {
  !assay.getUnitOps().isEmpty(units);
  // no use rights present in units ${units}`;
}
```

This function does not really do anything (doesn't return, doesn't throw) and there is a possible typo between `asset` and `assay`

**Comment by Chris-Hibbert** [comment]
This now depends on the `insist()` in ERTP/util/insist.js. When the flag is false, a template is expanded and thrown in an Error.

It looks like the documentation hasn't kept up with changes in the API. @katelynsills, is this a small, local update, or does it need a more pervasive re-write?

**Comment by katelynsills** [comment]
@Chris-Hibbert I think this `insist` function is not the same thing as the ERTP `insist` and was created for the documentation. I don't know the backstory on it, but it's possible we could just take it out.

**Comment by Chris-Hibbert** [comment]
Yes, I think all the discussion under `assay.getUnitOps()` in the [API doc for Assays](https://github.com/Agoric/documentation/blob/master/main/ertp/api/assay.md) should go away. It seems to have been cribbed from the [pixel gallery](https://github.com/Agoric/agoric-sdk/blob/master/packages/ERTP/more/pixels/gallery.js). The pixel gallery no longer defines its own `insist()` function, and in any case, the discussion there isn't really relevant to `assay.getUnitOps()`
