### ISSUE TITLE
Document Snippet of getting and using the RUN issuer

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#468]
Here's a snippet:

```
  const moneyIssuer = await E(home.agoricNames).lookup('issuer', 'RUN');
  const moneyBrand = await E(moneyIssuer).getBrand();

  const allCardNames = harden(cards);
  const pricePerCard = amountMath.make(10n, moneyBrand);

  const {
    sellItemsPublicFacet: publicFacet,
    sellItemsInstance: instance,
  } = await E(baseballCardSellerFacet).sellCards(
    allCardNames,
    moneyIssuer,
    sellItemsInstallation,
    pricePerCard,
  );
```

See https://github.com/Agoric/dapp-card-store/pull/18 for more.

The more generalized pattern is:

```
  const moneyIssuer = await E(home.agoricNames).lookup('issuer', 'RUN');
E(zoe).startInstance(installation, harden({ Money: moneyIssuer }), terms);
```

**Comment by dckc** [comment]
https://docs.agoric.com/guides/integration/name-services.html#agoricnames-agoricnamesadmin-well-known-names

plus more in dapp-agoric-basics and #985

https://github.com/Agoric/dapp-agoric-basics/blob/1b7c376328fb2c3cb6a50a32b645c0a0b539732c/contract/src/sell-concert-tickets.proposal.js#L65

https://dc-deploy-contract.documentation-7tp.pages.dev/guides/coreeval/proposal.html
