### ISSUE TITLE
Document Treasury code and highlight in Dapps section

### ISSUE THREAD

**Issue by rowgraus** [Agoric/documentation#472]

**Comment by Tartuffo** [comment]
@rowgraus This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract

**Comment by Tartuffo** [comment]
@rowgraus Bump.  For proper project planning and tracking, this needs an area label covered by one of our weekly planning meetings.  Please pick the appropriate one from: agd, agoric-cli, agoric-cosmos, amm, core economy, cosmic-swingset, endo, ertp, getrun, governance, installation-bundling, metering, oracle, pegasus, run-protocol, ses, staking, swingset, swingset-runner, tc39, token economy, tooling, ui, wallet, xsnap, zoe, zoe contract

**Comment by Tyrosine22** [comment]
Is this still relevant?

**Comment by dckc** [comment]
I think this is addressed by Rowland's post:

 - [Inter Protocol Vaults: Contract Implementations \- Inter Protocol \- Agoric Community Forum](https://community.agoric.com/t/inter-protocol-vaults-contract-implementations/261)
