### ISSUE TITLE
Why does ERTP provide its own makePromise instead of standard Promises?

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#48]
Asking @katelynsills for instance

**Comment by katelynsills** [comment]
MakePromise is just a wrapper around regular promises. We might be using it
too often when we could just use regular Promises. In SwingSet, we remove
some cruft that Node adds to Promises in MakePromise.

**Comment by tyg** [comment]
Kate explained it, didn't really suggest making any changes to docs.
