### ISSUE TITLE
zoe docs should recommend  throw seat.fail(Error)

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#494]
See https://github.com/Agoric/agoric-sdk/issues/3026

The docs for `zcfSeat.fail` should recommend 
```
   throw seat.fail(Error('you did it wrong');
```
when exiting a seat with an error condition. It might even be helpful to cross-direct there from `seat.exit()` to say that error conditions shouldn't use `exit()`.

**Comment by tyg** [comment]
Fixed in [PR 495](Fix for issue 494; elaborate on how ZCF.fail is used #495)
