### ISSUE TITLE
Migrate to Vuepress V2

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#513]
Vuepress V1 is no longer supported, so security vulnerabilities in dependencies aren't getting fixed.

V2 is still in beta, but we may be able to move now. The other alternative is to stay on V1 but know that we can't easily upgrade the dependencies. https://github.com/vuepress/vuepress-next

See https://github.com/Agoric/documentation/pull/512

**Comment by Tyrosine22** [comment]
I can't figure out how to find out what version of vuepress we're currently using, so I have no idea if this bug is outdated. I'll have to come back & figure this out at a later date.

**Comment by dckc** [comment]
overtaken by vitepress update
