### ISSUE TITLE
Update ZCFMint docs

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#516]
We need to update https://agoric.com/documentation/zoe/api/zoe-contract-facet.html#zcf-makezcfmint-keyword-assetkind

The function `makeZCFMint` actually has three parameters:

```
/**
 * @callback MakeZCFMint
 * @param {Keyword} keyword
 * @param {AssetKind=} assetKind
 * @param {AdditionalDisplayInfo=} displayInfo
 * @returns {Promise<ZCFMint>}
 */
```

The displayInfo would include things like { decimalPlaces: 16 }

**Comment by tyg** [comment]
Close with [PR 517](https://github.com/Agoric/documentation/pull/517)
