### ISSUE TITLE
Document new Zoe APIs

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#551]
There are several new features of Zoe that aren't visible in our public doc. There are [private parameters](https://github.com/Agoric/agoric-sdk/pull/3576) to `startInstance`, plus all the changes for charging fees.

I don't know what else was added in the recent rush.

I routinely look stuff up in the docs, so it would be nice if they could be brought up to date.

**Comment by katelynsills** [comment]
A note on the fees - there's a question of how much we want to document given that we may be revising quite a bit as we learn more.

**Comment by Chris-Hibbert** [comment]
For the write-up on fees, I'm fine with documentation marked "Draft" or "tentative", and that we don't spend a lot of time on details for now, but there should at least be a placeholder for people who are experimenting with our system and encounter the need to include those params.

**Comment by katelynsills** [comment]
> For the write-up on fees, I'm fine with documentation marked "Draft" or "tentative", and that we don't spend a lot of time on details for now, but there should at least be a placeholder for people who are experimenting with our system and encounter the need to include those params.

Yup, agreed.
