### ISSUE TITLE
Update instructions for getting the source code

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#567]
This is indeed stale documentation. There is currently a way to get at
source. Eventually, Zoe will only have direct access to the hash.

On Mon, Oct 25, 2021 at 11:40 AM Dan Connolly ***@***.***>
wrote:

> One of our fans noticed installation.bundle.source in
> E(zoe).getInstallation(invitation)
> <https://agoric.com/documentation/zoe/api/zoe.html#e-zoe-getinstallation-invitation>
> .
>
> Is that documentation now out of date?
>
> Do we plan to restore the ability to get source code?
>
> you can get the original source code of any contract as a built-in feature
> of the SDK. In Ethereum someone tells you a hardcoded address, then you ask
> an explorer for the source, AFAIK. In Agoric, you can access it in the base
> API.
> -- https://twitter.com/least_nathan/status/1451273772577685504
>
> I suppose that means you can even do automated source code analysis within
> contracts?
>
> Scifi: Imagine something like "my contract will only send withdrawals to
> destinations with code that type checks and meets these other static
> analysis guarantees".
> -- https://twitter.com/least_nathan/status/1451273774418980866
>

_Originally posted by @kriskowal in https://github.com/Agoric/agoric-sdk/issues/3871#issuecomment-951271233_

**Comment by kriskowal** [comment]
Tagging @samsiegart since we discussed UI work on this recently.

**Comment by Tartuffo** [comment]
@kriskowal @samsiegart This is in the "Up Next" pipeline, but does not have a MN-1 label.  If it is needed for MN-1, please label, otherwise move from "Up Next" to "Product Backlog".

**Comment by Tartuffo** [comment]
I'm taking this out of "Up Next" and throwing into the generic "Product Backlog" pipeline.

**Comment by kriskowal** [comment]
I addressed the issue with documentation a while back. Elsewhere, we’re tracking API changes that expose the bundle hash in Zoe and even possibly hide the sources from Zoe. I’m closing this and relying on us to remember to update the documentation has this use case evolves per https://github.com/Agoric/agoric-sdk/issues/3871
