### ISSUE TITLE
hardened js setup guide leads to broken eslint processes

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#588]
Following the steps outlined in the "Hardened JavaScript" section of the docs results in eslint not working as it should. You can view this repository which has been created by following the steps outlined in the docs:

https://github.com/tgrecojs/jessie.js-eslint-repo

I can update this issue with steps for fixing this problem if it would be useful. it's my understanding that the missing links are one of (or a combination) of the following steps:
* adding the "processor" property as outlined in [jessie/packages/eslint-plugin](https://github.com/tgrecojs/Jessie/tree/main/packages/eslint-plugin#usage).
* installing the `@typescript-eslint/parser` package alongside `@jessie.js/eslint-config`

**Comment by tgrecojs** [comment]
tagging @dckc for exposure purposes

**Comment by dckc** [comment]
@michaelfig bonus points if you beat me to addressing this one.

**Comment by tgrecojs** [comment]
just a heads up - pushed a `fix` branch that resolves the issue. not sure if it solves the root cause, but looks as though the eslintConfig.extends array is looking for a different reference of the jessie eslint plugin. 


whereas i thought there might be a need for the `typescript-parser` package, it seemed to be as simple as changing the string from `jessie` to plugin:@jessie.js/recommended`. didn't even need `processor` property mentioned in endo/jessie.js repo 🙂 



branch is here - [fix branch](https://github.com/tgrecojs/jessie.js-eslint-repo/tree/fix) the only change is the following  tho:

```json
  "eslintConfig" : {
      "extends": [
        "plugin:@jessie.js/recommended"
      ]
 }
```
