### ISSUE TITLE
Links for the treasury contract code

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#594]
Noticed that the page for the Treasury contract doesn't follow suit with the rest of the contract docs in having any links to the contract code. Not sure if this was done purposely, or if it stemmed from the contract code living outside of of the `packages/zoe` folder, but felt it worth mentioning after I found myself clicking around the page looking for the link 🙂 

Didn't want to just open up a PR for it but if this isn't an intended feature then i'm happy to do so. Just need signing off on linking to the contract even tho it lives within it's own package, as well as if the link should route to a specific file or instead linking to the [src](https://github.com/Agoric/agoric-sdk/tree/master/packages/treasury/src) directory.

**Comment by dckc** [comment]
"Treasury" is passe
