### ISSUE TITLE
Documentation pages slow to refresh after a while

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#606]
I keep a Brave window open in a corner of my screen with the doc site open so I can look up Zoe or ERTP APIs or whatever. When it has sat unused for a while, the navigation gets unresponsive.  I've gotten used to this enough that when I see navigation going slowly (the progress bar crawling along) I hit the browser refresh button, and after that, navigation is fairly speedy.

I think it effects all the tabs simultaneously. I only have to refresh one of the tabs to make them all responsive.

**Comment by tgrecojs** [comment]
- @Chris-Hibbert can you confirm whether or not this behavior is consistent across different browsers? I mainly utilize Firefox Developer Edition cant recall ever running into this (or at least i can't recall an instance when I did 🙂). 

I have experienced Brave work a bit odd at times though, so I'm wondering if this is one of those instances?

**Comment by Chris-Hibbert** [comment]
This has been noticeable for months, but now that I've reported it, it seems to have gone away. Not reproducible in the original environment--Brave-- nor anywhere else at the moment.
