### ISSUE TITLE
document node version policy: LTS (and note v14 vs M1)

### ISSUE THREAD

**Issue by kennyrowe** [Agoric/documentation#627]
## Describe the bug
When building the SDK with a mac M1 the final build step fails

## To Reproduce
1. Using Node 14.15
2. Followed instructions for building with apple silicon (ie, install canvas)
3. `yarn  install` 
4. `yarn build`
5.  error
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@endo/init'
```

## Platform Environment
 - agoric-sdk version cc79ff6
 - Node version 14.15
 - Macbook pro M1 max chip

## Additional context
Tried adding package with `yarn add @endo/init` and got

```
yarn add v1.22.15
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by tgrecojs** [comment]
> I'm not sure I follow. [Agoric/agoric-sdk#4460](https://github.com/Agoric/agoric-sdk/pull/4460) was because [Agoric/agoric-sdk#4420](https://github.com/Agoric/agoric-sdk/pull/4420), which was merged after this issue was opened, introduced a dev dependency that has a higher node version requirement, so we bumped up our CI image.

Ah, sorry for misinterpreting. My knowledge of ARM vx. x86 arch only begun when getting this M1 so apologies for being so green. 


> I'm not sure which arch or from where you installed node.js, but the official package for Node 14 does not support the M1 architecture, only the x86 emulation. That is nothing specific to this repo.

FWIW, I installed node via NVM. Running the `node -p process.arch` prints arm64. Below are some relevant contents i got from inspecting `process` within my terminals node repl.

```sh
  arch: 'arm64',
  platform: 'darwin',
  release: {
    name: 'node',
    lts: 'Fermium',
    sourceUrl: 'https://nodejs.org/download/release/v14.17.6/node-v14.17.6.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v14.17.6/node-v14.17.6-headers.tar.gz'
  },
 ```
 
Thanks for all the info here! @mhofman

**Comment by Tartuffo** [comment]
Devs on M1 need to use V16.

**Comment by dtribble** [comment]
node 14.18 seems to work. I cloned `agoric-sdk` again. `yarn && yarn build` succeeded.

**Comment by Tyrosine22** [comment]
Because we cover the installation of Node in the Getting Started section, I'll handle this when I revise that section... a revision which is scheduled for the relatively near future.

**Comment by dckc** [comment]
This just about covers it:
> ```
> node --version # LTS version such as 18.16.0
> ```
https://docs.agoric.com/guides/getting-started/#install-node-js

Ideally, the text above it would use the same "LTS version such as 18.16.0" wording, but it says "We recommend installing the LTS version of node 18" as if there are non-LTS versions of node 18 and as if we don't recommend v20 once it becomes LTS.
