### ISSUE TITLE
ZCash Gardening Club: Hello Zoe, Jessie, IBC, ...

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#628]
"bookmarking" this until it has a better home...

[Dan Connolly at ZCash Gardening Club \- YouTube](https://www.youtube.com/watch?v=icAcjD8G6Ak)
Dec 7, 2021

incl:
 - 4:30 to 10:30 high speed fly-over of [Offer Safety: Partitioning Risk  in Smart Contracts](https://docs.google.com/presentation/d/1wptY1WJIk3hfM2EHOCQ62fdSGXr0uPbRdckfXDO6yhM/edit#slide=id.p) slides by Kate Sills, 2019-12
 - 12:30 to 24:00 Hands-on with Zoe contracts and Jessie
   - hello world
     - note: fits in [a tweet](https://twitter.com/DeanTribble/status/1433268983977820161)
   - your 2nd zoe contract: points for primes

**Comment by Chris-Hibbert** [comment]
@erights says "It is now public and on 'Agoric Talks' ".

**Comment by dckc** [comment]
I went over some of this "intro to Zoe" stuff with @jessysaurusrex and @Tartuffo in preparation for Restival. TODOs:

 - be prepared to run tests
   - put the stuff in github so folks can play with it
 - be prepared to demo the "fire the missiles" hardened js example
 - find the graphic of the contract host and seats

**Comment by dckc** [comment]
@jessysaurusrex and co, a little project with the hello-world and points-for-primes contracts is now at https://github.com/dckc/zoe-first-steps#readme

**Comment by dckc** [comment]
in double-checking that the tests work and such, I refined them a bit and started integrating them into the Agoric documentation on a [dc-zoe-intro branch](https://github.com/Agoric/documentation/tree/dc-zoe-intro/snippets/zoe/contracts):

 - [hello-zoe.js](https://github.com/Agoric/documentation/blob/dc-zoe-intro/snippets/zoe/contracts/hello-zoe.js)
 - [hello-zoe-rw.js](https://github.com/Agoric/documentation/blob/dc-zoe-intro/snippets/zoe/contracts/hello-zoe-rw.js)
 - [test-hello.js](https://github.com/Agoric/documentation/blob/dc-zoe-intro/snippets/zoe/contracts/test-hello.js)
 - [points-for-primes.js](https://github.com/Agoric/documentation/blob/dc-zoe-intro/snippets/zoe/contracts/points-for-primes.js)
 - [test-primes.js](https://github.com/Agoric/documentation/blob/dc-zoe-intro/snippets/zoe/contracts/test-primes.js)

**Comment by tgrecojs** [comment]
@dckc i edited ur talk into 2 separate videos according the timestamps specified in ur response below.

> incl:
> 
>     * 4:30 to 10:30 high speed fly-over of [Offer Safety: Partitioning Risk  in Smart Contracts](https://docs.google.com/presentation/d/1wptY1WJIk3hfM2EHOCQ62fdSGXr0uPbRdckfXDO6yhM/edit#slide=id.p) slides by Kate Sills, 2019-12
> 
>     * 12:30 to 24:00 Hands-on with Zoe contracts and Jessie
>       
>       * hello world
>         
>         * note: fits in [a tweet](https://twitter.com/DeanTribble/status/1433268983977820161)
>       * your 2nd zoe contract: points for primes


The videos are unlisted on YouTube but can be viewed at the links below:

1. [Dan Connolly at ZCash Gardening Club - Video #1](https://youtu.be/7rQn-HiZBbg)
2. [Dan Connolly at ZCash Gardening Club - Video #2](https://youtu.be/wFs75ho-AdI)

let me know if there's any problem accessing them

**Comment by Tartuffo** [comment]
@tgrecojs I could not view those unlisted videos, I got "Video unavailable / This video has been removed by the uploader".

**Comment by dckc** [comment]
@Tartuffo the links work for me from this github page. You might be trying links from an email copy of an earlier version of the comment; those indeed have been removed.

**Comment by dckc** [comment]
I think the [sell1.js](https://gist.github.com/dckc/0988dfe516c24a1e925a1d68b3a69217#file-sell1-js) contract from yesterday's intro to zoe is a much better example: https://github.com/Agoric/documentation/issues/576#issuecomment-1332566399

cc @cboydstun @Tyrosine22

**Comment by Tyrosine22** [comment]
I'm confused: What bug, ask, or task is this ticket highlighting?
