### ISSUE TITLE
Update documentation on Treasury

### ISSUE THREAD

**Issue by turadg** [Agoric/documentation#630]
A request was made in https://github.com/Agoric/agoric-sdk/pull/4686#issuecomment-1054688673 to document the changes.

For example, [here](https://github.com/Agoric/documentation/blob/c73a3c5aa80fdc6c6571658461d6f30a313cc49a/main/zoe/guide/contracts/treasury.md?plain=1#L75-L81 ):

- need to rename `uiNotifier` to `vaultNotifier`
- need to add `assetNotifier`

I notice that the article overall is stale such as the omission of TransferVault and that the title is "Treasury", which I believe has been renamed to avoid confusion.

The article will need a full once-over before MN-1 release so I'm queuing that up here.

**Comment by Tyrosine22** [comment]
Is this still relevant?

**Comment by dckc** [comment]
`treasury.md` seems to be gone.
