### ISSUE TITLE
Chaos Engineering Questiom

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#631]
The use of chaos engineering has been an emerging trend for teams building large scale frontend systems in order to best ensure that they possess the ability to function properly when faced with adversity.

I'm wondering if Agoric has an opinion on whether partaking in chaos engineering would be considered a best practice for those building client-facing applications on agoric's
blockchain? Or if this is a decision that agoric believes development teams should evaluate and decide upon internally, rather than taking a particular stance on it. 

## relevant links
* https://blog.twitch.tv/en/2022/01/10/automated-chaos-testing-on-the-front-end/
* https://gremlin.com
* https://github.com/dastergon/awesome-chaos-engineering

**Comment by dckc** [comment]
We don't have a particular stance on it.
