### ISSUE TITLE
Following in-page anchors incompletely updates browser history

### ISSUE THREAD

**Issue by gibson042** [Agoric/documentation#636]
Reproduction steps:
1. Navigate to https://agoric.com/documentation/glossary/ .
2. Click "**AssetHolder**" in the sidebar. Observe that the page scrolls to the AssetHolder section, the sidebar is styled to indicate the new selection, and the URL fragment updates accordingly.
3. Click the "**amount**" link. Observe corresponding changes in the sidebar, URL, and page scroll position.
4. Navigate back (e.g., with the browser button). Observe that the sidebar and URL update, but the page does not scroll.
5. Click the "**value**" link under Amounts. Observe corresponding changes in the sidebar, URL, and page scroll position.
6. Navigate back (e.g., with the browser button). Observe that the sidebar and URL update (to "AssetHolder" because of the previous back-navigation), but the page does not scroll.

**Comment by Tyrosine22** [comment]
Unable to reproduce; it seems to be working OK.

**Comment by gibson042** [comment]
Fixed now, possibly by #840.
