### ISSUE TITLE
economic governance parameters: ranges, risks

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#653]
for governance parameters such as MintingRatio, document plausible range of values and risks associated with a setting that is too high or too low.

ref: https://github.com/Agoric/agoric-sdk/pull/4741
see also: https://github.com/Agoric/agoric-sdk/issues/4828

cc @turadg @rowgraus @btulloh @Chris-Hibbert

**Comment by Tyrosine22** [comment]
I'll tackle this when I tackle Governance in general (#749)

**Comment by dckc** [comment]
I suppose that's one way to go about it, but note that this is more about risks associated with operation of the Inter Protocol contracts in particular than the governance framework in general.

One option is to close this for the same reason I closed https://github.com/Agoric/agoric-sdk/issues/5046 : the parameters are documented for the community in product docs (by @otoole-brendan and co):

 - <a href="https://docs.inter.trade/inter-protocol-system-documentation/protocol-and-chain-governance">Protocol &amp; Chain Governance - Inter Protocol User &amp; System Docs</a>

We don't go much into risks of getting the parameters too high or too low there, but those parameters are managed by the Economic Committee; I think they keep some internal documentation of these matters.

If someone else wanted to deploy the Inter Protocol docs, they might appreciate documentation on the risks around setting the minting limit etc. too high or too low. But that's pretty low priority compared to a lot of other documentation.

I wonder if this report says much about economic risks associated with the governance parameters in the Inter Protocol contracts...

 - [Inter Protocol Smart Contract Implementation](https://agoric.com/wp-content/uploads/2022/10/Final-Atredis-Partners-Agoric-Inter-Protocol-Assessment-v1.1.pdf) Atredis Partners, Q3 2022

no, I don't see much about it.

**Comment by dckc** [comment]
no longer seems cost-effective to document this here
