### ISSUE TITLE
Cosmos / tendermint RPC doc links

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#657]
@gibson042 you said you want pointers to the current stuff. Can we put the answer in this issue until we get it in our docs?

@warner you said you had a couple bookmarks?
@michaelfig what do you use?

IOU a couple pointers: gift.js that uses cosmjs, and request1bld.js that does a tx search by sender

**Comment by michaelfig** [comment]
I search for "tendermint swagger" and "cosmos chain swagger" and I get:

- [Tendermint RPC](https://docs.tendermint.com/master/rpc/)
- [Cosmos v0.44.5 RPC](https://v1.cosmos.network/rpc/v0.44.5) need to twiddle the version selector at the top right hand side if you want different versions.  v0.44.5 is closest to the one we're using in agoric-sdk.

**Comment by dckc** [comment]
> IOU a couple pointers: gift.js that uses cosmjs, and

https://github.com/Agoric/faucet/blob/cosmjs-rpc/src/gift.js
currently: https://github.com/Agoric/faucet/blob/35c4bb7/src/gift.js

> request1bld.js that does a tx search by sender

https://github.com/Agoric/testnet-notes/blob/1bld-sheet/subm/src/request1bld.js
currently: https://github.com/Agoric/testnet-notes/blob/ca26fb2/subm/src/request1bld.js

that imports:
https://github.com/Agoric/testnet-notes/blob/1bld-sheet/subm/src/tendermintRPC.js
https://github.com/Agoric/testnet-notes/blob/ca26fb2/subm/src/tendermintRPC.js

**Comment by dckc** [comment]
Some Q&A re mainnet0:

Q: What API version are we running on our RPC nodes?
A: Whatever is aligned with agoric-upgrade-5 which is v0.44.5-alpha.agoric.ag0.5

main.api.agoric.net = cosmos lcd == https://v1.cosmos.network/rpc/v0.37.9
main.rpc.agoric.net = tendermint rpc == https://docs.tendermint.com/master/rpc/

for example: https://main.api.agoric.net/cosmos/tx/v1beta1/txs/73765FA0F7A33ADD808A6A5A24338BCC375DCA6D70B5653BB9310CFEE3FC1B09

**Comment by dckc** [comment]
[Interchain Developer Academy](https://interchainacademy.cosmos.network/) seems to be good stuff.

For example, [Consensus in Distributed Networks](https://interchainacademy.cosmos.network/ida-course/0-blockchain-basics/4-consensus.html#)

Thanks, @Tyrosine22 , for helping me find it again.

**Comment by Tyrosine22** [comment]
I'm glad I could be of service. Can we either close this bug or move it to another database? It doesn't seem like an active doc bug.

**Comment by dckc** [comment]
Not an active doc bug? It seems to me that the cosmos level of our chain should be documented.
Other Cosmos-SDK chains _copy_ the relevant docs; for example: `junod keys add <new-key-name> --recover` is documented in https://docs.junonetwork.io/cli/useful-cli-commands . Our system has an analog, `agd keys add ...` but we don't document it except for a few examples in our validator guide wiki pages. It seems to me that the least we could do is _point_ to the docs for the version of cosmos-sdk that we're based on.

**Comment by dckc** [comment]
A couple related pointers:

https://interchainacademy.cosmos.network/tutorials/3-run-node/ discusses `simd keys list`, on which `agd keys list` is based.

https://github.com/cosmos/gaia/blob/main/docs/delegators/delegator-guide-cli.md discusses `gaiad tx gov submit-proposal`, on which `agd tx gov submit-proposal` is based.

We tend to rely on keplr docs and "come delegate with us!" tutorials by validators for delegator docs. But it might be nice to copy the delegator guide into our docs.

For MN-2 smart contract devs we really should document `gaiad tx gov submit-proposal`.

**Comment by dckc** [comment]
I suppose the CLI should get its own issue, separate from documenting the network protocol(s).

But there are a few different audiences for the CLI:
  - delegators
  - node operators
  - app devs / testers

**Comment by dckc** [comment]
addressed by https://docs.agoric.com/guides/integration/chain-integration.html , more or less

I took one more look at these; I think we cover the essential stuff from there, along with relevant links...

https://ida.interchain.io/tutorials/1-tech-terms/#rpc-and-the-interchain
https://docs.cosmos.network/main/learn/advanced/grpc_rest#grpc-gateway-rest-routes
