### ISSUE TITLE
Update AssetKind references to include COPY_SET and COPY_BAG

### ISSUE THREAD

**Issue by gibson042** [Agoric/documentation#665]
As done in https://github.com/Agoric/documentation/commit/85fc794f2ae83a44045458d9a94c53e96074447d#diff-567699eff5882f854f56340cee0537815d3e363b61e098208212dc172190dd3dR43 :
> `AmountMath` has a single set of polymorphic methods that deal with different asset kinds:
> - `AssetKind.NAT`: Used with [fungible](#fungible) assets.
>   Each amount value is a natural number (non-negative integer).
>   This is the default `AssetKind`.
> - `AssetKind.SET`: Used with [non-fungible](#non-fungible) assets;
>   deprecated in favor of `AssetKind.COPY_SET` but still in wide use.
>   Each amount value is an array of [Key](#key) values
>   subject to the same constraints as those of `AssetKind.COPY_SET`.
> - `AssetKind.COPY_SET`: Used with [non-fungible](#non-fungible) assets.
>   Each amount value is a set of [Key](#key) values
>   (strings, numbers, objects, etc.).
>   Values cannot include promises (they aren't keys), and should not
>   include privileged objects such as payments and purses.
> - `AssetKind.COPY_BAG`: Used with [semi-fungible](#semi-fungible) assets.
>   Each amount value is a [multiset](https://en.wikipedia.org/wiki/Multiset)
>   of [Key](#key) values subject to the same constraints as
>   those of `AssetKind.COPY_SET` but allowed to be present more than once.

**Comment by dckc** [comment]
lack of documentation for COPY_BAG came up in office hours today:
https://gist.github.com/dckc/9c393be1bd5a147f72c6b42ca12a1aa2#semi-fungible-tokens
https://github.com/Agoric/agoric-sdk/issues/4657

**Comment by Tyrosine22** [comment]
This has been addressed. See https://docs.agoric.com/reference/ertp-api/ertp-data-types.html#assetkind.
