### ISSUE TITLE
Zoe "Fees and Metering" file is obsolete

### ISSUE THREAD

**Issue by gibson042** [Agoric/documentation#675]
As noted by @erights at https://github.com/Agoric/documentation/pull/673/files/c6270756bb4c8c2531f9bd3230664edd7f61893c#r872908215 , Zoe does not charge fees. main/zoe/api/fees-and-metering.md should be reviewed for accuracy, and likely removed entirely.

**Comment by Tyrosine22** [comment]
I'm not sure who owns the documentation within the product repo.

**Comment by dckc** [comment]
`fees-and-metering.md` seems to be gone.
