### ISSUE TITLE
update the **Watch: Prepare Your Agoric Environment (Nov 2020)** video

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#685]
@tgrecojs feel like another PR to replace the **Watch: Prepare Your Agoric Environment (Nov 2020)** video with the one @kennyrowe did this May? https://www.youtube.com/watch?v=VrXlGwKh0zk

_Originally posted by @dckc in https://github.com/Agoric/documentation/issues/652#issuecomment-1184971670_

**Comment by Tyrosine22** [comment]
I'd like to eliminate this particular video; text is just as clear & much easier to maintain.

**Comment by dckc** [comment]
currently tracked as

 - #893
