### ISSUE TITLE
document API for blocking Zoe invitations

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/documentation#686]
https://github.com/Agoric/agoric-sdk/issues/5036   added the ability to block invitations to a Zoe contract by calling `zcf.setOfferFilter()`. This needs to be added to the documentation.

**Comment by Tyrosine22** [comment]
I'm documenting this in the course of my Zoe API revisions

**Comment by dckc** [comment]
fixed in https://docs.agoric.com/guides/governance/#offer-filters
