### ISSUE TITLE
Revise RUN terminology

### ISSUE THREAD

**Issue by turadg** [Agoric/documentation#689]
"RUN Protocol" --> Inter Protocol

RUN brand --> IST brand

contract keywords updated

**Comment by cboydstun** [comment]
Sorry I can't find "RUN Protocol" nor "RUN brand" to replace in any of the documentation files. Please advise. 😬 @turadg

**Comment by turadg** [comment]
Looks like @arirubinstein did this in https://github.com/Agoric/documentation/pull/698
