### ISSUE TITLE
"Start Coding" link

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#705]
Reading through the documentation, I am finding that there is a bit of noise that gets in the way of trying to have developers begin coding.

Twice on the initial page of the docs, this "start coding" link appears, but it only leads to another page of text, as opposed to any content that actually gets devs up an running with the agoric sdk.

<img width="766" alt="Screen Shot 2022-08-19 at 12 23 53 PM" src="https://user-images.githubusercontent.com/6646552/185652891-e1d5ee1c-e4eb-41a2-a02c-949264cf2e82.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/6646552/185653254-c7d4252e-d923-4812-bab6-6e431bcd9b1a.png">

Opening up this issue to see if we should change this layout. I suggest changing the text in the first image from "start coding" to "Learn more about getting started with the agoric SDK". For the second image, I would link to the [quick start](https://docs.agoric.com/getting-started/before-using-agoric.html#quick-start).

Any thoughts on this? CC @dckc

**Comment by dckc** [comment]
> Reading through the documentation, I am finding that there is a bit of noise that gets in the way of trying to have developers begin coding.

completely agree.

Those screenshots though... hurl me an url? Where does that text occur?

**Comment by tgrecojs** [comment]
> Those screenshots though... hurl me an url? Where does that text occur?

here it is - https://docs.agoric.com/getting-started/beta.html

**Comment by cboydstun** [comment]
[pull request 712 ](https://github.com/Agoric/documentation/pull/712)

**Comment by dckc** [comment]
Let's hold off on closing until the PR is reviewed and merged. In fact, github will close it automatically if the pr says it closes this.

**Comment by cboydstun** [comment]
branch merged and deleted last Friday https://github.com/Agoric/documentation/pull/712
