### ISSUE TITLE
add `numWantsSatisfied` to Zoe API docs

### ISSUE THREAD

**Issue by cboydstun** [Agoric/documentation#711]
"UserSeat `numWantsSatisfied` gives a promise that settles once the seat has exited. It settles to 0 if the wants are not satisfied, and it settles to > 0 if the wants are satisfied. Currently (pre multiples) the wants are either not satisfied (0) or satisfied exactly once (1). But to be future compat better to test for 0 vs > 0.
Offer safety guarantees that if the wants are not satisfied (0) then all the escrowed assets are refunded. But note that even if the wants are satisfied, you may still receive a full refund anyway. That’s why the relevant UI question is usually whether the wants are satisfied." - @erights 

where should it go and what should it say? @Tartuffo

**Comment by Tartuffo** [comment]
I'm guessing somewhere in https://docs.agoric.com/getting-started/intro-zoe.html but nothing there is really detailed (yet)

**Comment by erights** [comment]
Attn @Chris-Hibbert

**Comment by cboydstun** [comment]
I'd be happy to get this documented, but cannot find a similar use case in the Zoe introduction as proposed above and am reluctant to enter the definition elsewhere. Please advise thanks! =) @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
`numWantsSatisfied()` is a method on a [Zoe userSeat](https://docs.agoric.com/zoe/api/zoe.html#userseat-object). The holder of the seat can call it before the seat has exited. It returns a promise that settles once the seat has exited. 

The format of the response was determined by the planned enhancement we call "multiples". It's not worth explaining that plan in the doc for `numWantsSatisfied`, but it might be worth mentioning that "future enhancement" is the rationale.

The UI often wants to report to the user whether their offer was successfully processed. Zoe's main concern is offer safety, so the platform doesn't have a single definition of success that is meaningful across all possible contracts. Nevertheless, we find that a common question is "did the user get what they expressed in their `want`?"  Once the seat exits, the promise resolves to a positive integer (1 for now, but possibly larger after the enhancement) if the user got their `want`.  If they got their `give` back and didn't receive their want, then the value will be zero.

**Comment by erights** [comment]
In case it becomes relevant, https://github.com/Agoric/agoric-sdk/pull/5422 is the multiples PR.

**Comment by Tyrosine22** [comment]
I've taken a look at the method's source code; what it tries to do doesn't seem all that complicated. I'll document this method when I revise the Zoe API docs. I'm not sure when exactly that'll be.

**Comment by Tyrosine22** [comment]
This method was documented as part of my Zoe API revision effort.
