### ISSUE TITLE
Agoric.com Homepage "Start Building" button redirects to 404

### ISSUE THREAD

**Issue by cboydstun** [Agoric/documentation#725]
## Describe the bug
Clicking the "Start Building" button on our homepage redirects to a 404 link. However, the redirects have been made on the documentation VuePress side and refreshing will display the correct page. Suggest changing button link on homepage from[ it's current address](https://agoric.com/documentation/getting-started/before-using-agoric.html) to the [updated documentation address](https://docs.agoric.com/guides/getting-started/). 

## To Reproduce
1. Go to 'www.agoric.com'
2. Click on 'Start Building'
3. Experience 404. 
4. Click "Refresh" and page renders correctly. 

## Expected behavior
Should display the[ "Installing the Agoric SDK" docs page](https://docs.agoric.com/guides/getting-started/).
 
## Platform Environment
 - Windows Google Chrome

## Screenshots
Homepage
![image](https://user-images.githubusercontent.com/52934303/200640727-28586a9e-e23d-432c-bcb3-de880b8cfaf9.png)
404
![image](https://user-images.githubusercontent.com/52934303/200640783-5d6f14f8-d8fd-41bf-8b7a-c310b6ca633d.png)
Refresh
![image](https://user-images.githubusercontent.com/52934303/200640817-ae681405-4c0e-4682-852d-b44357162f62.png)

**Comment by cboydstun** [comment]
Thought you wanted to be in on the loop. 

I'll remove you until we need the big guns. @dckc  💪

**Comment by Tyrosine22** [comment]
Ari thinks the problem is that we need to use Cloudflare's link redirect mechanism rather than .vuepress' mechanism... so a different file needs to be used and the syntax is slightly different. I'll be spending time this afternoon trying to get the Cloudflare mechanism to work.

**Comment by Tyrosine22** [comment]
This has  been fixed.
