### ISSUE TITLE
transition getting started from ag-solo to smart wallet + RPC

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#726]
docs talk about ag-solo and such,
but production uses a [smart wallet architecture](https://docs.agoric.com/guides/getting-started/contract-rpc.html)

Tangentially related: efforts to make installing the SDK from npm more straightforward:

 - https://github.com/Agoric/agoric-sdk/issues/3857

cc @michaelfig @turadg @samsiegart

**Comment by turadg** [comment]
This is great. To get this rendering natively in Github we could massage it into a [C4 diagram](https://mermaid-js.github.io/mermaid/#/c4c). E.g.

```mermaid
    C4Context
      title System Context diagram for Internet Banking System
      Enterprise_Boundary(b0, "BankBoundary0") {
        Person(customerA, "Banking Customer A", "A customer of the bank, with personal bank accounts.")
        Person(customerB, "Banking Customer B")
        Person_Ext(customerC, "Banking Customer C", "desc")

        Person(customerD, "Banking Customer D", "A customer of the bank, <br/> with personal bank accounts.")

        System(SystemAA, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")

        Enterprise_Boundary(b1, "BankBoundary") {

          SystemDb_Ext(SystemE, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

          System_Boundary(b2, "BankBoundary2") {
            System(SystemA, "Banking System A")
            System(SystemB, "Banking System B", "A system of the bank, with personal bank accounts. next line.")
          }

          System_Ext(SystemC, "E-mail system", "The internal Microsoft Exchange e-mail system.")
          SystemDb(SystemD, "Banking System D Database", "A system of the bank, with personal bank accounts.")

          Boundary(b3, "BankBoundary3", "boundary") {
            SystemQueue(SystemF, "Banking System F Queue", "A system of the bank.")
            SystemQueue_Ext(SystemG, "Banking System G Queue", "A system of the bank, with personal bank accounts.")
          }
        }
      }

      BiRel(customerA, SystemAA, "Uses")
      BiRel(SystemAA, SystemE, "Uses")
      Rel(SystemAA, SystemC, "Sends e-mails", "SMTP")
      Rel(SystemC, customerA, "Sends e-mails to")

      UpdateElementStyle(customerA, $fontColor="red", $bgColor="grey", $borderColor="red")
      UpdateRelStyle(customerA, SystemAA, $textColor="blue", $lineColor="blue", $offsetX="5")
      UpdateRelStyle(SystemAA, SystemE, $textColor="blue", $lineColor="blue", $offsetY="-10")
      UpdateRelStyle(SystemAA, SystemC, $textColor="blue", $lineColor="blue", $offsetY="-40", $offsetX="-50")
      UpdateRelStyle(SystemC, customerA, $textColor="red", $lineColor="red", $offsetX="-50", $offsetY="20")

      UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")
```

**Comment by dckc** [comment]
This overlaps substantially with:

 - #758 
 - #748

**Comment by anilhelvaci** [comment]
What is the latest state on documenting the smart wallet? Can you point me to some docs if any.

**Comment by turadg** [comment]
> What is the latest state on documenting the smart wallet? Can you point me to some docs if any.

@anilhelvaci I've linked to some in https://github.com/Agoric/documentation/issues/748#issuecomment-1419084918

**Comment by anilhelvaci** [comment]
> @anilhelvaci I've linked to some in [#748 (comment)](https://github.com/Agoric/documentation/issues/748#issuecomment-1419084918)

Thanks 🙏

**Comment by dckc** [comment]
## Smart Wallet app development with local-chain, Core Eval web form

In [Nov 1 office hours](https://github.com/Agoric/agoric-sdk/discussions/8489), we demo'd a [zero-to-dapp approach](https://github.com/Agoric/agoric-sdk/discussions/8480#discussioncomment-7446658):

1. a dapp such as [dapp-join-game](https://github.com/agoric-labs/dapp-join-game) to buy some NFTs comes with support for starting a local chain with a `yarn start:docker` command that uses `docker-compose` to start a chain with all the facilities from mainnet, based on work in [agoric-3-proposals](https://github.com/Agoric/agoric-3-proposals)

```console
~/projects/simple-game$ yarn start:docker                                                                                                               
yarn run v1.22.19                                                                                                                                                       
$ docker-compose up -d                                                                                                                                                  
Creating network "simple-game_default" with the default driver                                                                                                          
Creating simple-game_agd_1 ... done                                                                                                                                     
Done in 0.56s.
```

Having it run in 0.56s like that depends on...
 - https://github.com/Agoric/agoric-3-proposals/pull/11

Plus, the first time they do it, the computer will spend a minute or so downloading the image.

 - The [Gov Proposal Builder](https://agoric-gov-proposal-hub.netlify.app/) lets devs drag-and-drop their bundles and their script/permit of their contract, built with a simple `yarn build:proposal` command.

![image](https://github.com/Agoric/documentation/assets/150986/7b7ba150-96d0-4ab0-84bf-acd0a136f9fc)

![image](https://github.com/Agoric/documentation/assets/150986/10273cf7-58d0-4627-b05f-697655a9f648)


Bundling their contract still depends on being able to install the Agoric SDK; we're close to being able to do that smoothly from npm (https://github.com/Agoric/agoric-sdk/issues/3857)

**Comment by dckc** [comment]
## notes from trying it out

@kbennett2000 ran into trouble as soon as he tried to `yarn install` at the top. some sqlite3 build error. Sigh.

He also ran into `command not found` for `docker-compose`.

When we switched to my screen...

`yarn docker:mint4k` didn't work - files  have moved around
note: came from list in 
 - https://github.com/agoric-labs/dapp-join-game/pull/2

The `user1` key/address had changed, so I did import-to-keplr thing again. But our devs will have to do that at least once.
Here's hoping not more than once:
 - https://github.com/Agoric/agoric-3-proposals/issues/5

By the time I went to submit a CoreEval, my initial 10BLD had been reduced to 7.6 or so, so I had to get more to meet the required 10 BLD deposit.

Having a `contract` directory inside the UI stuff is awkard:

  - https://github.com/samsiegart/simple-game/issues/3

`yarn test` didn't work at all...

 - [ ] TODO: migrate contract tests

```
simple-game/contract$ yarn ava
yarn run v1.22.19
warning package.json: No license field
$ /home/connolly/projects/simple-game/contract/node_modules/.bin/ava

  ✘ Couldn’t find any files to test
```

**Comment by dckc** [comment]
a few thinks to double-check with @sufyaankhan ...

 - [ ] title of `/geting-started/` page? was "Installing the Agoric SDK"; now "Your First Agoric Dapp". is that right?

**Comment by dckc** [comment]
well, #894 is deployed. So let's call this done after all.
