### ISSUE TITLE
confusion around checking proposal shapes (featuring `M`)

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#739]
It's unclear how to properly check an offer's proposal shape, so I'm opening this issue to get clarity around the matter. 

vscode informed me of `assertProposalShape` being deprecated, which led me to find [this issue](https://github.com/Agoric/agoric-sdk/pull/6072#issue-1352755872). In that issue, @erights informs us that `zcf.makeInvitation` takes an optional `proposalSeat` parameter which, if supplied, will be used by Zoe to verify an offer proposal. He also mentions that users can request information about the shape of an invitations `proposalSeat` from Zoe. 

I understood this to mean that the `proposalShape` parameter would mirror the parameters used in `assertProposalShape,` but after several attempts, it was clear that this wasn't the case. I investigated a bit and couldn't find any instances in which this new approach was used. I found [`fitProposalShape`](https://github.com/Agoric/agoric-sdk/blob/master/packages/zoe/src/contractSupport/zoeHelpers.js#L117-L119) inside the zoeHelpers.js file so I made an attempt to use that directly in my contract, but again, I had no luck.

Among the things I discovered while investigating was the use of agoric/store's [`M`](https://github.com/Agoric/agoric-sdk/blob/master/packages/store/src/patterns/patternMatchers.js#L1706-L1821) being used to construct [what looks as though it may be a valid `proposalShape`](https://github.com/Agoric/agoric-sdk/blob/7844f693d638ea823e076589bf808309d242fd3c/packages/zoe/src/typeGuards.js#L27-L45).

In addition to my confusion around understanding `proposalShape`s, this also led me to realize I lacked any knowledge of the aforementioned `M` API. 

Is the agoric documentation a suitable place for this information? It looks fairly robust and seems to be used quite a bit throughout the agoric-sdk, so I imagine that users of the SDK would benefit to have knowledge of it.

**Comment by erights** [comment]
See also https://github.com/Agoric/agoric-sdk/wiki/Interfaces for the main current use of patterns. Has nothing to do with `proposalShape`, but it is most of the pattern examples you'll encounter.
