### ISSUE TITLE
Document Governance

### ISSUE THREAD

**Issue by Tyrosine22** [Agoric/documentation#749]

**Comment by Chris-Hibbert** [comment]
We need to write guidelines for contract authors on how to use the governance framework, and for contract reviewers on how to verify that a contract is following the process correctly, and where to look for violations. There's some of the latter in the [Attacker's Guide](https://github.com/Agoric/agoric-sdk/blob/master/packages/governance/docs/AttackGuide.md), but it should be made more systematic.

Some links:
 * [contractGovernor](https://github.com/Agoric/agoric-sdk/blob/5fcfe1a89c3db7af00143385d10d60910694e5c0/packages/governance/src/contractGovernor.js#L68)
 * [contractHelper](https://github.com/Agoric/agoric-sdk/blob/5fcfe1a89c3db7af00143385d10d60910694e5c0/packages/governance/src/contractHelper.js#L205)
 * search for `CRUCIAL` in .../governance/.
 *

**Comment by dckc** [comment]
closed in #999
