### ISSUE TITLE
Update Cosmic-Swingset README and move to documentation repo

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#75]
We need to update the [Cosmic-Swingset README](https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/README.md)  and move it to this documentation repo. 

Cross posted to agoric-sdk repo as https://github.com/Agoric/agoric-sdk/issues/548

**Comment by tyg** [comment]
Covered on the user side by "Starting Multiuser Dapps" in the [Agoric CLI Guide](/distributed-programming.md)
