### ISSUE TITLE
Document Durability, Upgrade

### ISSUE THREAD

**Issue by Tyrosine22** [Agoric/documentation#750]
**User Story:** As a Developer I should be able to read the docs and understand how to make contract durable and upgradable (Using the dapp-agoric-basics as context)

**Comment by dckc** [comment]
See also https://github.com/Agoric/agoric-sdk/discussions/5708

**Comment by dckc** [comment]
Does this include upgrade?

> We don't yet have a theory of upgradeable contracts. When we do, we need to write that up. -- https://github.com/Agoric/agoric-sdk/pull/5635

**Comment by dckc** [comment]
be sure to make the point about 1st crank, as in https://github.com/Agoric/agoric-sdk/pull/8721#discussion_r1472070049

**Comment by dckc** [comment]
more source material:

https://github.com/endojs/endo/blob/master/packages/exo/docs/exo-taxonomy.md#heap-vs-virtual-vs-durable

https://github.com/Agoric/agoric-sdk/blob/master/packages/store/docs/store-taxonomy.md#ephemeral-vs-durable-only-big-stores-can-be-durable


Oh: https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/vat-upgrade.md#zone-api includes the view from zones, which is much better!
