### ISSUE TITLE
Revise the REPL API docs

### ISSUE THREAD

**Issue by Tyrosine22** [Agoric/documentation#752]

**Comment by dckc** [comment]
Most of what's in the REPL section should probably go under a section on the `home` object, which is referenced from docs on both the REPL and deploy scripts.

**Comment by dckc** [comment]
#727 points out that `namesByAddress`, `myAddressNameAdmin` are not documented, nor the whole `NameHub` API.

cc @gibson042

**Comment by dckc** [comment]
dup of

 - #617
