### ISSUE TITLE
Get a Simple asset trade dapp working

### ISSUE THREAD

**Issue by Tyrosine22** [Agoric/documentation#761]

**Comment by dckc** [comment]
looks like lots of overlap with:

  - #744

**Comment by dckc** [comment]
Mostly for testing, @samsiegart expressed interest in building a UI around [gameAssetContract.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/test/gameAssetContract.js). But that might serve this purpose, to some extent.

**Comment by dckc** [comment]
@samsiegart made a [simple smart wallet app](https://github.com/samsiegart/simple-game) (context: https://github.com/Agoric/ui-kit/pull/37 ).

**Comment by dckc** [comment]
fixed as part of

 - #726 

Meanwhile, see also:

 - https://github.com/alexanderem49/simple-exchange/issues/32
