### ISSUE TITLE
Fix or reimplement the doc project linkchecker.

### ISSUE THREAD

**Issue by Tyrosine22** [Agoric/documentation#762]

**Comment by dckc** [comment]
What's wrong with it? What are the symptoms?

**Comment by Tyrosine22** [comment]
I found several cases where the tool simply didn't catch broken internal links. I really should have included locations of these uncaught broken links in the bug, but... I didn't. Later this week I'll go through my notes & add the examples to the bug.

More about the uncaught broken links:

I couldn't find any rhyme or reason as to which broken links weren't caught... it seemed completely random. Obviously, figuring out the pattern will be step 1 to fixing the tool. Because I don't know how extensive the "missed broken links" problem is, I currently have low faith in the tool's efficacy. I mean, it's better than no tool, and I use it, but it's far from ideal.

**Comment by dckc** [comment]
seems to work as of the vitepress update
