### ISSUE TITLE
Document how mint configuration works

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#78]
After https://github.com/Agoric/agoric-sdk/issues/375 , things have changed quite a bit and the [current doc](https://agoric.com/documentation/ertp/guide/default-configuration.html#what-is-a-configuration) does not really reflect it yet
Built-in extentOps (soon "amountMath") need to be there as well

**Comment by tyg** [comment]
Page link now returns a 404, and mint docs appear up to date.
