### ISSUE TITLE
add state sync to node start documentation

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#792]
https://docs.agoric.com/guides/getting-started/syncing-up.html is somewhat onerous due to [lack of state sync support](https://github.com/Agoric/agoric-sdk/issues/3769). But that's due to change any time now: https://github.com/Agoric/agoric-sdk/pull/7225 

That PR says:
> Documentation Considerations
> Nothing special besides normal cosmos state-sync instructions.

looking around, I find:

 - https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-mainnet.md#state-sync
 - https://github.com/tendermint/tendermint/blob/v0.34.x/spec/p2p/messages/state-sync.md

cc @mhofman @michaelfig @Tyrosine22 @Just-a-Lorax @arirubinstein @ivanlei

**Comment by mhofman** [comment]
We could also link to validator operating docs like https://polkachu.com/state_sync/agoric
