### ISSUE TITLE
Broken  `Developer Bounties` link on agoric.com

### ISSUE THREAD

**Issue by RuslanGlaznyov** [Agoric/documentation#803]
I can't find the source code of agoric.com, so I decided to write it here.  

On the community page 
https://agoric.com/community
we have a `Discover the bounty` button, but it has the wrong link 
https://www.gitcoin.co/agoric/bounties -> 404
the correct one: 
https://bounties.gitcoin.co/agoric/bounties

**Comment by dckc** [comment]
thanks for the feedback! expect an update shortly.

**Comment by ivanlei** [comment]
Will be updated to https://components.agoric.com/bounties/open-bounties .

**Comment by ivanlei** [comment]
This has been resolved. Thanks again for the bug report.
