### ISSUE TITLE
Vstorage diagram has a typo

### ISSUE THREAD

**Issue by gibson042** [Agoric/documentation#853]
https://docs.agoric.com/guides/getting-started/contract-rpc.html#querying-vstorage uses `E(invbrandNodeNode)` rather than `E(brandNode)`.

**Comment by Chris-Hibbert** [comment]
The easiest way to get this fixed is to scroll to the bottom of the page where it says *Help us improve this page!*, and submit a fix. I can approve it quickly, and it'll be up on the website in a jiffy.

**Comment by gibson042** [comment]
I already opened a PR at #854; this issue exists so it has something to fix.
