### ISSUE TITLE
Getting started is missing a step explaining wallet locator

### ISSUE THREAD

**Issue by mhofman** [Agoric/documentation#856]
Following the [Getting started](https://docs.agoric.com/guides/getting-started/start-a-project.html) documentation, I got stuck at the step to "Connect the Dapp to the Agoric Wallet" apparently because I first needed to point the [wallet locator](https://wallet.agoric.app/locator) to my local ag-solo backed wallet (`http://localhost:8000`). This is apparently [explained in the readme of the demo dapp](https://github.com/Agoric/dapp-card-store/#using-the-dapp), but that's not very discoverable

![image](https://github.com/Agoric/documentation/assets/86499/231225e4-adb1-4e25-a2bc-49900da50a67)

**Comment by dckc** [comment]
wallet locator is an aspect of the ag-solo / beta design, which we have transitioned away from

 - #726
 - #894
 - #896 
 - #897
