### ISSUE TITLE
Document Invitation Specs

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/documentation#878]
As a developer, I should be able to learn about Invitation Specs and design patterns for communicating offers to and from a smart-wallet.

```
invitationSpec: {
  source: 'contract' | 'agoricContract' | 'purse' | 'continuing';
  instancePath: [ string ];
  callPipe: [];
  invitationMakerName:  [ string ];
  previousOffer: string;
  invitationArgs: [];
  description: string;
  publicInvitationMaker: string;
}
```

**Comment by 0xpatrickdev** [comment]
See #667 for the original issue

**Comment by dckc** [comment]
@erights asked about "call pipe"

call pipe is a poor-man's expression language used to encode things like `E(E(vaultFactory).getManagerForBrand(atomBrand)).makeVaultInvitation()`

see AgoricContractInvitationSpec https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/invitations.js#L25

I'm struggling to find tests. I think they use this utility...

https://github.com/Agoric/agoric-sdk/blob/6e90d9640a7129584540b2028198e92a7b6e32c4/packages/inter-protocol/src/clientSupport.js#L88-L95

```js
    invitationSpec: {
      source: 'agoricContract',
      instancePath: ['VaultFactory'],
      callPipe: [
        ['getCollateralManager', [collateralBrand]],
```

**Comment by dckc** [comment]
oops... I merged the invitation spec docs that I added to #999 on governance without review, didn't I?

@0xPatrick @turadg @sam @hibbert showed interest at various times.

Please see **InvitationSpec Usage** under [Specifying Offers](https://docs.agoric.com/guides/getting-started/contract-rpc.html#specifying-offers).
