### ISSUE TITLE
video walk-thru of getting started

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#893]
@kbennett2000 is working on this

It depends on a few things...

 - [x] https://github.com/agoric-labs/dapp-game-places/issues/16
 - [x] https://github.com/agoric-labs/dapp-game-places/issues/13
 - [ ] add walkthru to `/getting-started/` page

**Comment by kbennett2000** [comment]
Video Walkthrough here:
https://youtu.be/nczDihk8Nvs

**Comment by kbennett2000** [comment]
Raw file -- https://drive.google.com/file/d/1BW8Q8tuftCQ7feoyKS1X6pS7D7SrNU2g/view?usp=drive_link

**Comment by dckc** [comment]
fixed in #920
