### ISSUE TITLE
Document _agstate folder

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/documentation#924]
`_agstate` and `_agstate/agoric-servers` folders are present in almost all dApps that I looked at, for example, https://github.com/Agoric/dapp-offer-up/tree/main/_agstate. However it's not clear to me, a developer new to Agoric platform, why `_agstate` is needed, especially considering it only contains a boilerplate `package.json` file.

[This commit](https://github.com/Agoric/dapp-offer-up/commit/302bd54e07656e4eab0ae5e678905e5810a1efee) seems to suggest `_agstate` is here to make `agoric install` happy, but some explanation around why it's needed, what's its purpose, and when should a developer use it would be great!

**Comment by dckc** [comment]
It's a vestige of ag-solo / sim chain / beta architecture. @sufyaankhan has asked that we omit that stuff from the docs.

I presume it's OK to close this. Feel free to re-open it if that seems in order.

For reference, an earlier PR where I started flagging such stuff:

 - https://github.com/Agoric/documentation/pull/837

**Comment by dckc** [comment]
that reminds me: `yarn create @agoric/dapp ...` fails without an `_agstate` dir. That's the only reason dapp-offer-up has one. We should fix that:

 - https://github.com/Agoric/agoric-sdk/issues/8817

**Comment by LuqiPan** [comment]
I think I tried to start up `dapp-offer-up` without the `_agstate` dir and I wasn't able to start the dapp, might be I did something dumb though.

**Comment by dckc** [comment]
Right; there are some vestigial things that break when `_agstate` is removed. https://github.com/Agoric/agoric-sdk/issues/8817 is about getting rid of those.
