### ISSUE TITLE
Docs Revamp | Design overhaul

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#932]
We need a design overhaul of our docs.

"Its not what we say, its how we say it"

Display content in the following format: (inspired by Cosmology)

<img width="1140" alt="Screenshot 2024-01-25 at 2 20 16 PM" src="https://github.com/Agoric/documentation/assets/143552737/d5ab33ac-7c28-4b26-9d64-44e7cd87a8b8">

<img width="1144" alt="Screenshot 2024-01-25 at 2 21 19 PM" src="https://github.com/Agoric/documentation/assets/143552737/4021e127-140b-4b89-8450-cf0b6d3688c0">

**Comment by dckc** [comment]
> We need a design overhaul of our docs.

It helps if we document the motivation for such things.

**Comment by dckc** [comment]
assigning this to @0xpatrickdev since #996 seems likely to address this

**Comment by 0xpatrickdev** [comment]
Closed by #996 and #1018
