### ISSUE TITLE
Page 1 - How to deploy a smart contract

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#935]
Goal: Create a (Lesson plan + video) that shows the code and explainer for the following:

- How to deploy a smart contract | with Code sample

**Comment by kbennett2000** [comment]
Video:
<iframe width="560" height="315" src="https://www.youtube.com/embed/XT1S4E1h-jM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Instructions:
Ensure Node is installed in your environment. If you need to install Node in your environment you can follow the steps here --> https://docs.agoric.com/guides/getting-started/#installing-nvm-and-node

Ensure Yarn is installed in your environment. If you need to install Yarn in your environment you can follow the steps here --> https://docs.agoric.com/guides/getting-started/#installing-yarn

Clone the Agoric SDK from the Agoric GitHub repo:
``sh
git clone https://github.com/Agoric/agoric-sdk
``

Go to SDK folder:
``sh
cd agoric-sdk
``

Run the Yarn commands:
``sh
yarn install
yarn build
``

Add the Agoric bin folder to your PATH variable:
``sh
export PATH=$PATH:/home/agoric/bin
``

Link the CLI to the bin folder:
``sh
yarn link-cli ~/bin/agoric
``

Check to ensure the SDK is installed:
``sh
agoric --version
``

Create a new project:
``sh
cd ..
agoric init testProject
cd testProject
``

Install the Agoric components:
``sh
agoric install
``

Start a local chain:
``sh
agoric start
``

**Comment by kbennett2000** [comment]
2/1 - In progress...

**Comment by kbennett2000** [comment]
Ready for you review @sufyaankhan

**Comment by kbennett2000** [comment]
https://github.com/Agoric/documentation/pull/976

**Comment by sufyaankhan** [comment]
Looks good to me. Approved. FYI @kbennett2000

**Comment by dckc** [comment]
#976 is not merged

**Comment by dckc** [comment]
fixed in ##1066
