### ISSUE TITLE
Page 1 - How to initiate an offer | with Code sample

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#936]
Goal: Create a (Lesson plan + video) that shows the code and explainer for the following:

- How to initiate an offer | with Code sample

**Comment by kbennett2000** [comment]
https://github.com/Agoric/documentation/blob/kbennett2000-patch-1/main/guides/getting-started/Explainer%20-%20How%20to%20Make%20an%20Offer.md

**Comment by kbennett2000** [comment]
Ready for your review @sufyaankhan

**Comment by kbennett2000** [comment]
https://github.com/Agoric/documentation/pull/976

**Comment by sufyaankhan** [comment]
Looks good to me. Approved. FYI @kbennett2000

**Comment by dckc** [comment]
fixed in #1066
