### ISSUE TITLE
Page 2 - Code the Dapp-Agoric-Basic Skeleton

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#938]
Page 2:

Goal: 1 Frontend test and 1 Contract test + lint - to start running this dapp.

 - same developer tooling (`yarn start:docker`, ...) as dapp-offer-up
 - Dapp-Agoric-Basics need to use the same tooling as Dapp-Offer-Up.

**Comment by dckc** [comment]
See:
 - [Creating Your Dapp From a Template](https://docs.agoric.com/guides/getting-started/#creating-your-dapp-from-a-template)

**Comment by dckc** [comment]
Switching to the [cosgov ui](https://github.com/DCFoundation/cosmos-proposal-builder) in #939 _after_ starting from a template  might be awkward - different lint settings etc.

@0xpatrickdev it would be nice to have a dapp template that has all that sorted out. I think @ivanlei mentioned that possibility to me at some point. I suppose that merits another ticket. What do you think?
