### ISSUE TITLE
Document what an zoe offer being "active" means

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#94]
It's not clear to me from the existing doc and API what "(in)active" means. It's also unclear for me how to change a status from one to the other or when/why such a change happens

ping @katelynsills

**Comment by katelynsills** [comment]
Very good point that we need to explain this better. 

An active offer is after the step of redeeming an invite and escrowing with Zoe, but before the offer is completed.

**Comment by tyg** [comment]
Done.
