### ISSUE TITLE
normalize markdown formatting style

### ISSUE THREAD

**Issue by dckc** [Agoric/documentation#945]
vs-code keeps reformatting markdown files when I save them. I presume it's using prettier or the like. I could turn it off, I suppose, but perhaps it's better to set up tooling to do this uniformly?

**Comment by kbennett2000** [comment]
I'm in favor of running all our code through something to make it look uniform, and I think prettier is what most folks are using? Anyway, the more consistent we can make things look to a new developer, the better IMO...
