### ISSUE TITLE
Vstorage journey - 4daydapp

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#947]
**User Story:** As a Developer I should be able to read the docs and understand what vstorage is, how I can leverage vstorage, how it should be used in the context of the dapp-agorics-basics

E.g. vstorage is a journey of requesting powers within a core-eval, creating a storage node, passing the storage node in privateArgs to a contract, using the storage node within a contract, reading from vstorage via raw HTTPS or ui-kit.

**Comment by dckc** [comment]
[Querying VStorage](https://docs.agoric.com/guides/getting-started/contract-rpc.html#querying-vstorage) has a relevant diagram. It only shows querying with `agd` and `agoric follow`, not HTTP nor ui-kit.

**Comment by dckc** [comment]
In order for a UI to show the remaining inventory, the contract should probably publish the allocation of `inventorySeat` to vstorage. @LuqiPan here's hoping I can have docs sufficient for you to do that after we land PR 8.

https://github.com/Agoric/dapp-agoric-basics/pull/8#discussion_r1486630828

**Comment by dckc** [comment]
This seems to include #758 .

**Comment by dckc** [comment]
re vstorage reference docs, I'm leaving this somewhat obscure stuff to a discussion...

 - https://github.com/Agoric/agoric-sdk/discussions/9115

**Comment by dckc** [comment]
more on reference docs...

 - [test-vstorage-ref.js.md](https://github.com/Agoric/dapp-agoric-basics/blob/dc-vstorage-ref/contract/test/snapshots/test-vstorage-ref.js.md) WIP
