### ISSUE TITLE
Timer device docs - 4daydapp

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#948]
**User Story:** As a Developer I should be able to read the docs and understand what is Timer device and how should Developers use it? (use Dapp-Agoric-basics as context)

**Comment by dckc** [comment]
We have some reference docs: https://docs.agoric.com/reference/repl/timerServices.html

They could use some updating, though.

cc @kbennett2000

**Comment by Chris-Hibbert** [comment]
This [internal doc](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/timer.md) is more up-to-date than the documentation site.

**Comment by dckc** [comment]
yeah... in #1022 I'm trying out `typedoc`:
https://github.com/Agoric/documentation/blob/dc-price-authority/main/api-docs/interfaces/agoric_time.TimerService.md
