### ISSUE TITLE
[Zoe] Improve explanation around "redeem" step

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#95]
We currently say something like the following in zoe.chainmail

```
   * To redeem an invite, the user normally provides a proposal (their rules for the
   * offer) as well as payments to be escrowed by Zoe.  If the proposal or payments are
   * undefined, the default is not to propose or pay (just to obtain the invite's seat).
```

Possibly bike shed the name 'redeem'

**Comment by tyg** [comment]
How's this: (material in ()s is part of the suggested text. Except for bracketed material prefaced by "tyg" which is a comment)?

   * When responding to an invite, normally the user provides [tyg: maybe sends?] 
   * payments (that Zoe escrows) and a proposal (their rules for the offer). If either of 
   * these is undefined, by default  neither the proposal or payments are sent, but 
   * the user still obtains the invite's seat. [tyg: is this last correct?]

**Comment by katelynsills** [comment]
Ahh, I just realized this issue is stale. The quoted content actually never got merged into master because it was replaced by Mark's better suggestion: https://github.com/Agoric/agoric-sdk/blob/cf9346dde2a3fcea435af5149cb958aad5a8016d/packages/zoe/src/zoe.chainmail#L63

We can close this issue. Sorry for the confusion! In general, I think how we document redeem can be improved, so let me know if you think there's something still here in this issue to work with.
