### ISSUE TITLE
4daydapp - Document - What is Board

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#950]
**User Story:** As a Developer I should be able to read the docs and understand what is "Board" in Agoric systems and how should developers use it?

**Comment by dckc** [comment]
I recently did a [board section in naming services](https://docs.agoric.com/guides/integration/name-services.html#the-board-publishing-under-arbitrary-names). Seems to fit here.

If it's not enough, please re-open with details about what's missing.
