### ISSUE TITLE
4daydapp - Document - How does Governance work in Agoric?

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#952]
**User Story:** As a Developer I should be able to read the docs and understand how Governance works in Agoric systems. (use Dapp-Agoric-Basics as context)

**Comment by dckc** [comment]
related work: #749 esp. https://github.com/Agoric/documentation/issues/749#issuecomment-1502148745

**Comment by dckc** [comment]
I asked around for an example / test to work from and got

https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/test/auction/test-auctionContract.js#L112

Not all the testing tools it uses are available outside the SDK, so some adaptation is needed.

https://github.com/Agoric/agoric-sdk/blob/a3f0fc5d2cd48fa398491237b683d091b1003309/packages/inter-protocol/test/supports.js#L96-L111

**Comment by dckc** [comment]
closed in #999
