### ISSUE TITLE
Docs Revamp - Testing - writeup

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#962]
**User Story:** As a Developer I should be able to read the docs and understand how I can test my smart contracts in the Agoric ecosystem.

- Define the different tools I have at my disposal e.g. Ava 
- Define the process
- Define all the commands / steps

**Comment by dckc** [comment]
done: https://docs.agoric.com/guides/zoe/contract-basics.html#using-testing-a-contract
