### ISSUE TITLE
Docs Revamp - Organizing the Navigation

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#973]
Goal: To organize the Nav bar for the entire Docs site.

**Comment by dckc** [comment]
some prototyping: https://github.com/kbennett2000/agoric-slides

**Comment by dckc** [comment]
## Demote out-of-date pages from navigation

The [Wallet](https://docs.agoric.com/guides/wallet/) and [Wallet UI](https://docs.agoric.com/guides/wallet/ui.html) pages are outdated. I suggest omitting them from `nav.js` / `config.mjs`.

(For folks that _do_ manage to find them, the pages should probably have a beta notice as in #837, #904 . Is that in scope for this issue?)

Likewise the following pages that are currently in either the left or the top nav bar:

 - [Agoric Dapps \| Agoric Documentation](https://docs.agoric.com/guides/dapps/)
 - https://docs.agoric.com/guides/dapps/dapp-templates.html
 - [Starting Multiuser Dapps \| Agoric Documentation](https://docs.agoric.com/guides/dapps/starting-multiuser-dapps.html)
 - [Deploying Smart Contracts \| Agoric Documentation](https://docs.agoric.com/guides/getting-started/deploying.html)
 - [Chainlink Integration \| Agoric Documentation](https://docs.agoric.com/guides/chainlink-integration.html)
 - [Agoric REPL \| Agoric Documentation](https://docs.agoric.com/reference/repl/)

_originally in https://github.com/Agoric/documentation/pull/989#issuecomment-2002872045_

**Comment by dckc** [comment]
@sufyaankhan @kbennett2000 TIL that we have multiple sidebars (as of the vitepress transition?) So navigation updates should keep that in mind.
