### ISSUE TITLE
issues viewing docs across different viewports

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/documentation#988]
While veiwing the docs a moment ago I found myself viewing what i believe to be the layout for mid-sized screens. The "new features" section popped out to me, but I was met with no interactivity when i attempted to engage with the side bar.

Attached is a ~40 second video showing the behavior, and i also have some audio describing the issues i've found.

https://github.com/Agoric/documentation/assets/6646552/d929c131-0a30-40e9-8257-434eafd34710

**Comment by dckc** [comment]
new features is gone in recent updates

 - #1018
 - #1049

I don't see the behavior you describe any more.
