### ISSUE TITLE
Home Page Copy and Styles

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/documentation#998]
As part of #972, we have an opportunity to leverage the default vitepress theme to offer a cleaner UI when users navigate to docs.agoric.com.

A preview of this is live at #996, but needs copy from product. I imagine the final copy might not focus on the benefits exclusively, and would piggyback off of the proposed navigation structure - Tutorials, Core Concepts, How To. There's also an unimplemented footer section where we can link to discord, youtube, etc.

**Comment by dckc** [comment]
fixed in #996
